MotorWare f2802x Driver API Documentation: DRV8305
DRV8305
Data Structures
struct _DRV_SPI_8305_Stat01_t_
Object for the DRV8305 STATUS01 register.
struct _DRV_SPI_8305_Stat02_t_
Object for the DRV8305 STATUS02 register.
struct _DRV_SPI_8305_Stat03_t_
Object for the DRV8305 STATUS03 register.
struct _DRV_SPI_8305_Stat04_t_
Object for the DRV8305 STATUS04 register.
struct _DRV_SPI_8305_Ctrl05_t_
Object for the DRV8305 CTRL05 register.
struct _DRV_SPI_8305_Ctrl06_t_
Object for the DRV8305 CTRL06 register.
struct _DRV_SPI_8305_Ctrl07_t_
Object for the DRV8305 CTRL07 register.
struct _DRV_SPI_8305_Ctrl08_t_
Object for the DRV8305 CTRL08 register.
struct _DRV_SPI_8305_Ctrl09_t_
Object for the DRV8305 CTRL09 register.
struct _DRV_SPI_8305_Ctrl0A_t_
Object for the DRV8305 CTRL0A register.
struct _DRV_SPI_8305_Ctrl0B_t_
Object for the DRV8305 CTRL0B register.
struct _DRV_SPI_8305_Ctrl0C_t_
Object for the DRV8305 CTRL0C register.
struct _DRV_SPI_8305_Vars_t_
Object for the DRV8305 registers and commands.
struct _DRV8305_Obj_
Defines the DRV8305 object.
Macros
#define DRV8305_ADDR_MASK (0x7800)
Defines the address mask.
#define DRV8305_DATA_MASK (0x07FF)
Defines the data mask.
#define DRV8305_RW_MASK (0x8000)
Defines the R/W mask.
#define DRV8305_FAULT_TYPE_MASK (0x07FF)
Defines the R/W mask.
#define DRV8305_STATUS01_OTW_BITS (1 << 0)
Defines the location of the OTW (Over temperature warning) bits in the Status 1 register.
#define DRV8305_STATUS01_TEMP_FLAG3_BITS (1 << 1)
Defines the location of the TEMP_FLAG3 (Over temperature warning 3) bits in the Status 1 register.
#define DRV8305_STATUS01_TEMP_FLAG2_BITS (1 << 2)
Defines the location of the TEMP_FLAG2 (Over temperature warning 2) bits in the Status 1 register.
#define DRV8305_STATUS01_TEMP_FLAG1_BITS (1 << 3)
Defines the location of the TEMP_FLAG1 (Over temperature warning 1) bits in the Status 1 register.
#define DRV8305_STATUS01_VCPH_UVFL_BITS (1 << 4)
Defines the location of the VCPH_UVFL (Charge pump high, under voltage) bits in the Status 1 register.
#define DRV8305_STATUS01_VDS_STATUS_BITS (1 << 5)
Defines the location of the VDS_STATUS (Real time "OR" of 0x02[D5:D10]) bits in the Status 1 register.
#define DRV8305_STATUS01_PVDD_OVFL_BITS (1 << 6)
Defines the location of the PVDD_OVFL (PVDD over voltage) bits in the Status 1 register.
#define DRV8305_STATUS01_PVDD_UVFL_BITS (1 << 7)
Defines the location of the PVDD_UVFL (PVDD under voltage) bits in the Status 1 register.
#define DRV8305_STATUS01_TEMP_FLAG4_BITS (1 << 8)
Defines the location of the TEMP_FLAG4 (Over temperature warning 4) bits in the Status 1 register.
#define DRV8305_STATUS01_RESERVED1_BITS (1 << 9)
Defines the location of the RESERVED1 bits in the Status 1 register.
#define DRV8305_STATUS01_FAULT_BITS (1 << 10)
Defines the location of the FAULT (0-Warning, 1-Latched) bits in the Status 1 register.
#define DRV8305_STATUS02_SNS_A_OCP_BITS (1 << 0)
Defines the location of the SNS_A_OCP (Sense amp A over current) bits in the Status 2 register.
#define DRV8305_STATUS02_SNS_B_OCP_BITS (1 << 1)
Defines the location of the SNS_B_OCP (Sense amp B over current) bits in the Status 2 register.
#define DRV8305_STATUS02_SNS_C_OCP_BITS (1 << 2)
Defines the location of the SNS_C_OCP (Sense amp C over current) bits in the Status 2 register.
#define DRV8305_STATUS02_RESERVED1_BITS (1 << 3)
Defines the location of the RESERVED1 bits in the Status 2 register.
#define DRV8305_STATUS02_RESERVED2_BITS (1 << 4)
Defines the location of the RESERVED2 bits in the Status 2 register.
#define DRV8305_STATUS02_FETLC_VDS_BITS (1 << 5)
Defines the location of the FETLC_VDS (C low side, VDS Fault) bits in the Status 2 register.
#define DRV8305_STATUS02_FETHC_VDS_BITS (1 << 6)
Defines the location of the FETHC_VDS (C high side, VDS Fault) bits in the Status 2 register.
#define DRV8305_STATUS02_FETLB_VDS_BITS (1 << 7)
Defines the location of the FETLB_VDS (B low side, VDS Fault) bits in the Status 2 register.
#define DRV8305_STATUS02_FETHB_VDS_BITS (1 << 8)
Defines the location of the FETHB_VDS (B high side, VDS Fault) bits in the Status 2 register.
#define DRV8305_STATUS02_FETLA_VDS_BITS (1 << 9)
Defines the location of the FETLA_VDS (A low side, VDS Fault) bits in the Status 2 register.
#define DRV8305_STATUS02_FETHA_VDS_BITS (1 << 10)
Defines the location of the FETHA_VDS (A high side, VDS Fault) bits in the Status 2 register.
#define DRV8305_STATUS03_VCPH_OVLO_ABS_BITS (1 << 0)
Defines the location of the VCPH_OVLO_ABS (Charge pump high, absolute over voltage) bits in the Status 3 register.
#define DRV8305_STATUS03_VCPH_OVLO_BITS (1 << 1)
Defines the location of the VCPH_OVLO (Charge pump high, over voltage) bits in the Status 3 register.
#define DRV8305_STATUS03_VCPH_UVLO2_BITS (1 << 2)
Defines the location of the VCPH_UVLO2 (Charge pump high, under voltage 2) bits in the Status 3 register.
#define DRV8305_STATUS03_RESERVED1_BITS (1 << 3)
Defines the location of the RESERVED1 bits in the Status 3 register.
#define DRV8305_STATUS03_VCP_LSD_UVLO2_BITS (1 << 4)
Defines the location of the VCP_LSD_UVLO2 (Charge pump low, under voltage 2) bits in the Status 3 register.
#define DRV8305_STATUS03_AVDD_UVLO_BITS (1 << 5)
Defines the location of the AVDD_UVLO (AVDD regulator under voltage) bits in the Status 3 register.
#define DRV8305_STATUS03_VREG_UV_BITS (1 << 6)
Defines the location of the VREG_UV (VREG regulator under voltage) bits in the Status 3 register.
#define DRV8305_STATUS03_RESERVED2_BITS (1 << 7)
Defines the location of the RESERVED2 bits in the Status 3 register.
#define DRV8305_STATUS03_OTS_BITS (1 << 8)
Defines the location of the OTS (Over temperature shut down) bits in the Status 3 register.
#define DRV8305_STATUS03_WD_FAULT_BITS (1 << 9)
Defines the location of the WD_FAULT (Watchdog fault) bits in the Status 3 register.
#define DRV8305_STATUS03_PVDD_UVLO2_BITS (1 << 10)
Defines the location of the PVDD_UVLO2 (PVDD under voltage 2) bits in the Status 3 register.
#define DRV8305_STATUS04_RESERVED1_BITS (1 << 0)
Defines the location of the RESERVED1 bits in the Status 4 register.
#define DRV8305_STATUS04_RESERVED2_BITS (1 << 1)
Defines the location of the RESERVED2 bits in the Status 4 register.
#define DRV8305_STATUS04_RESERVED3_BITS (1 << 2)
Defines the location of the RESERVED3 bits in the Status 4 register.
#define DRV8305_STATUS04_RESERVED4_BITS (1 << 3)
Defines the location of the RESERVED4 bits in the Status 4 register.
#define DRV8305_STATUS04_RESERVED5_BITS (1 << 4)
Defines the location of the RESERVED5 bits in the Status 4 register.
#define DRV8305_STATUS04_FETLC_VGS_BITS (1 << 5)
Defines the location of the FETLC_VGS (C low side, VGS Fault) bits in the Status 4 register.
#define DRV8305_STATUS04_FETHC_VGS_BITS (1 << 6)
Defines the location of the FETHC_VGS (C high side, VGS Fault) bits in the Status 4 register.
#define DRV8305_STATUS04_FETLB_VGS_BITS (1 << 7)
Defines the location of the FETLB_VGS (B low side, VGS Fault) bits in the Status 4 register.
#define DRV8305_STATUS04_FETHB_VGS_BITS (1 << 8)
Defines the location of the FETHB_VGS (B high side, VGS Fault) bits in the Status 4 register.
#define DRV8305_STATUS04_FETLA_VGS_BITS (1 << 9)
Defines the location of the FETLA_VGS (A low side, VGS Fault) bits in the Status 4 register.
#define DRV8305_STATUS04_FETHA_VGS_BITS (1 << 10)
Defines the location of the FETHA_VGS (A high side, VGS Fault) bits in the Status 4 register.
#define DRV8305_CTRL05_IDRIVEP_HS_BITS (15 << 0)
Defines the location of the IDRIVEP_HS bits in the Control 5 register.
#define DRV8305_CTRL05_IDRIVEN_HS_BITS (15 << 4)
Defines the location of the IDRIVEN_HS bits in the Control 5 register.
#define DRV8305_CTRL05_TDRIVEN_BITS (3 << 8)
Defines the location of the TDRIVEN bits in the Control 5 register.
#define DRV8305_CTRL05_RESERVED1_BITS (1 << 10)
Defines the location of the RESERVED1 bits in the Control 5 register.
#define DRV8305_CTRL06_IDRIVEP_LS_BITS (15 << 0)
Defines the location of the IDRIVEP_LS bits in the Control 6 register.
#define DRV8305_CTRL06_IDRIVEN_LS_BITS (15 << 4)
Defines the location of the IDRIVEN_LS bits in the Control 6 register.
#define DRV8305_CTRL06_TDRIVEP_BITS (3 << 8)
Defines the location of the TDRIVEP bits in the Control 6 register.
#define DRV8305_CTRL06_RESERVED1_BITS (1 << 10)
Defines the location of the RESERVED1 bits in the Control 6 register.
#define DRV8305_CTRL07_TVDS_BITS (3 << 0)
Defines the location of the TVDS bits in the Control 7 register.
#define DRV8305_CTRL07_TBLANK_BITS (3 << 2)
Defines the location of the TBLANK bits in the Control 7 register.
#define DRV8305_CTRL07_DEAD_TIME_BITS (7 << 4)
Defines the location of the DEAD_TIME bits in the Control 7 register.
#define DRV8305_CTRL07_PWM_MODE_BITS (3 << 7)
Defines the location of the PWM_MODE bits in the Control 7 register.
#define DRV8305_CTRL07_COMM_OPT_BITS (1 << 9)
Defines the location of the COMM_OPT bits in the Control 7 register.
#define DRV8305_CTRL07_RESERVED1_BITS (1 << 10)
Defines the location of the RESERVED1 bits in the Control 7 register.
#define DRV8305_CTRL08_RESERVED_BITS (2047 << 0)
Defines the location of the RESERVED bits in the Control 8 register.
#define DRV8305_CTRL09_SET_VCPH_UV_BITS (1 << 0)
Defines the location of the SET_VCPH_UV bits in the Control 9 register.
#define DRV8305_CTRL09_CLR_FLTS_BITS (1 << 1)
Defines the location of the CLR_FLTS bits in the Control 9 register.
#define DRV8305_CTRL09_SLEEP_BITS (1 << 2)
Defines the location of the SLEEP bits in the Control 9 register.
#define DRV8305_CTRL09_WD_EN_BITS (1 << 3)
Defines the location of the WD_EN bits in the Control 9 register.
#define DRV8305_CTRL09_DIS_SNS_OCP_BITS (1 << 4)
Defines the location of the DIS_SNS_OCP bits in the Control 9 register.
#define DRV8305_CTRL09_WD_DLY_BITS (3 << 5)
Defines the location of the WD_DLY bits in the Control 9 register.
#define DRV8305_CTRL09_EN_SNS_CLAMP_BITS (1 << 7)
Defines the location of the EN_SNS_CLAMP bits in the Control 9 register.
#define DRV8305_CTRL09_DIS_GDRV_FAULT_BITS (1 << 8)
Defines the location of the DIS_GDRV_FAULT bits in the Control 9 register.
#define DRV8305_CTRL09_DISABLE_BITS (1 << 9)
Defines the location of the DISABLE bits in the Control 9 register.
#define DRV8305_CTRL09_FLIP_OTS_BITS (1 << 10)
Defines the location of the FLIP_OTS bits in the Control 9 register.
#define DRV8305_CTRL0A_GAIN_CS1_BITS (3 << 0)
Defines the location of the GAIN_CS1 bits in the Control A register.
#define DRV8305_CTRL0A_GAIN_CS2_BITS (3 << 2)
Defines the location of the GAIN_CS2 bits in the Control A register.
#define DRV8305_CTRL0A_GAIN_CS3_BITS (3 << 4)
Defines the location of the GAIN_CS3 bits in the Control A register.
#define DRV8305_CTRL0A_CS_BLANK_BITS (3 << 6)
Defines the location of the CS_BLANK bits in the Control A register.
#define DRV8305_CTRL0A_DC_CAL_CH1_BITS (1 << 8)
Defines the location of the DC_CAL_CH1 bits in the Control A register.
#define DRV8305_CTRL0A_DC_CAL_CH2_BITS (1 << 9)
Defines the location of the DC_CAL_CH2 bits in the Control A register.
#define DRV8305_CTRL0A_DC_CAL_CH3_BITS (1 << 10)
Defines the location of the DC_CAL_CH3 bits in the Control A register.
#define DRV8305_CTRL0B_VREG_UV_LEVEL_BITS (3 << 0)
Defines the location of the VREG_UV_LEVEL bits in the Control B register.
#define DRV8305_CTRL0B_DIS_PWRGD_BITS (1 << 2)
Defines the location of the DIS_PWRGD bits in the Control B register.
#define DRV8305_CTRL0B_SLP_DLY_BITS (3 << 3)
Defines the location of the SLP_DLY bits in the Control B register.
#define DRV8305_CTRL0B_RESERVED1_BITS (1 << 5)
Defines the location of the RESERVED1 bits in the Control B register.
#define DRV8305_CTRL0B_RESERVED2_BITS (1 << 6)
Defines the location of the RESERVED2 bits in the Control B register.
#define DRV8305_CTRL0B_RESERVED3_BITS (1 << 7)
Defines the location of the RESERVED3 bits in the Control B register.
#define DRV8305_CTRL0B_VREF_SCALING_BITS (3 << 8)
Defines the location of the VREF_SCALING bits in the Control B register.
#define DRV8305_CTRL0B_RESERVED4_BITS (1 << 10)
Defines the location of the RESERVED4 bits in the Control B register.
#define DRV8305_CTRL0C_VDS_MODE_BITS (7 << 0)
Defines the location of the VDS_MODE bits in the Control B register.
#define DRV8305_CTRL0C_VDS_LEVEL_BITS (31 << 3)
Defines the location of the VDS_LEVEL bits in the Control B register.
#define DRV8305_CTRL0C_RESERVED1_BITS (1 << 8)
Defines the location of the RESERVED1 bits in the Control B register.
#define DRV8305_CTRL0C_RESERVED2_BITS (1 << 9)
Defines the location of the RESERVED2 bits in the Control B register.
#define DRV8305_CTRL0C_RESERVED3_BITS (1 << 10)
Defines the location of the RESERVED3 bits in the Control B register.
Typedefs
typedef struct _DRV_SPI_8305_Stat01_t_ DRV_SPI_8305_Stat01_t_
Object for the DRV8305 STATUS01 register.
typedef struct _DRV_SPI_8305_Stat02_t_ DRV_SPI_8305_Stat02_t_
Object for the DRV8305 STATUS02 register.
typedef struct _DRV_SPI_8305_Stat03_t_ DRV_SPI_8305_Stat03_t_
Object for the DRV8305 STATUS03 register.
typedef struct _DRV_SPI_8305_Stat04_t_ DRV_SPI_8305_Stat04_t_
Object for the DRV8305 STATUS04 register.
typedef struct _DRV_SPI_8305_Ctrl05_t_ DRV_SPI_8305_Ctrl05_t_
Object for the DRV8305 CTRL05 register.
typedef struct _DRV_SPI_8305_Ctrl06_t_ DRV_SPI_8305_Ctrl06_t_
Object for the DRV8305 CTRL06 register.
typedef struct _DRV_SPI_8305_Ctrl07_t_ DRV_SPI_8305_Ctrl07_t_
Object for the DRV8305 CTRL07 register.
typedef struct _DRV_SPI_8305_Ctrl08_t_ DRV_SPI_8305_Ctrl08_t_
Object for the DRV8305 CTRL08 register.
typedef struct _DRV_SPI_8305_Ctrl09_t_ DRV_SPI_8305_Ctrl09_t_
Object for the DRV8305 CTRL09 register.
typedef struct _DRV_SPI_8305_Ctrl0A_t_ DRV_SPI_8305_Ctrl0A_t_
Object for the DRV8305 CTRL0A register.
typedef struct _DRV_SPI_8305_Ctrl0B_t_ DRV_SPI_8305_Ctrl0B_t_
Object for the DRV8305 CTRL0B register.
typedef struct _DRV_SPI_8305_Ctrl0C_t_ DRV_SPI_8305_Ctrl0C_t_
Object for the DRV8305 CTRL0C register.
typedef struct _DRV_SPI_8305_Vars_t_ DRV_SPI_8305_Vars_t
Object for the DRV8305 registers and commands.
typedef struct _DRV8305_Obj_ DRV8305_Obj
Defines the DRV8305 object.
typedef struct _DRV8305_Obj_ * DRV8305_Handle
Defines the DRV8305 handle.
typedef uint16_t DRV8305_Word_t
Defines the DRV8305 Word type.
Enumerations
enum DRV8305_CtrlMode_e { CtrlMode_Read = 1 << 15, CtrlMode_Write = 0 << 15 }
Enumeration for the R/W modes.
enum DRV8305_STATUS01_WarningWatchdog_e {
OTW = (1 << 0), TEMP_FLAG3 = (1 << 1), TEMP_FLAG2 = (1 << 2), TEMP_FLAG1 = (1 << 3),
VCPH_UVFL = (1 << 4), VDS_STATUS = (1 << 5), PVDD_OVFL = (1 << 6), PVDD_UVFL = (1 << 7),
TEMP_FLAG4 = (1 << 8), STAT01_RSV1 = (1 << 9), FAULT = (1 << 10)
}
Enumeration for the Status 1 register, warning and watchdog reset.
enum DRV8305_STATUS02_OvVdsFaults_e {
SNS_A_OCP = (1 << 0), SNS_B_OCP = (1 << 1), SNS_C_OCP = (1 << 2), STAT02_RSV2 = (1 << 3),
STAT02_RSV1 = (1 << 4), FETLC_VDS = (1 << 5), FETHC_VDS = (1 << 6), FETLB_VDS = (1 << 7),
FETHB_VDS = (1 << 8), FETLA_VDS = (1 << 9), FETHA_VDS = (1 << 10)
}
Enumeration for the Status 2 register, OV/VDS faults.
enum DRV8305_STATUS03_ICFaults_e {
VCPH_OVLO_ABS = (1 << 0), VCPH_OVLO = (1 << 1), VCPH_UVLO2 = (1 << 2), STAT03_RSV2 = (1 << 3),
VCP_LSD_UVLO2 = (1 << 4), AVDD_UVLO = (1 << 5), VREG_UV = (1 << 6), STAT03_RSV1 = (1 << 7),
OTS = (1 << 8), WD_FAULT = (1 << 9), PVDD_UVLO2 = (1 << 10)
}
Enumeration for the Status 3 register, IC faults.
enum DRV8305_STATUS04_VgsFaults_e {
STAT04_RSV5 = (1 << 0), STAT04_RSV4 = (1 << 1), STAT04_RSV3 = (1 << 2), STAT04_RSV2 = (1 << 3),
STAT04_RSV1 = (1 << 4), FETLC_VGS = (1 << 5), FETHC_VGS = (1 << 6), FETLB_VGS = (1 << 7),
FETHB_VGS = (1 << 8), FETLA_VGS = (1 << 9), FETHA_VGS = (1 << 10)
}
Enumeration for the Status 4 register, Vgs faults.
enum DRV8305_CTRL05_PeakSourCurHS_e {
ISour_HS_0p010_A = (0 << 0), ISour_HS_0p020_A = (1 << 0), ISour_HS_0p030_A = (2 << 0), ISour_HS_0p040_A = (3 << 0),
ISour_HS_0p050_A = (4 << 0), ISour_HS_0p060_A = (5 << 0), ISour_HS_0p070_A = (6 << 0), ISour_HS_0p125_A = (7 << 0),
ISour_HS_0p250_A = (8 << 0), ISour_HS_0p500_A = (9 << 0), ISour_HS_0p750_A = (10 << 0), ISour_HS_1p000_A = (11 << 0)
}
Enumeration for the high side gate drive peak source current.
enum DRV8305_CTRL05_PeakSinkCurHS_e {
ISink_HS_0p020_A = (0 << 4), ISink_HS_0p030_A = (1 << 4), ISink_HS_0p040_A = (2 << 4), ISink_HS_0p050_A = (3 << 4),
ISink_HS_0p060_A = (4 << 4), ISink_HS_0p070_A = (5 << 4), ISink_HS_0p125_A = (6 << 4), ISink_HS_0p250_A = (7 << 4),
ISink_HS_0p500_A = (8 << 4), ISink_HS_0p750_A = (9 << 4), ISink_HS_1p000_A = (10 << 4), ISink_HS_1p250_A = (11 << 4)
}
Enumeration for the high side gate drive peak sink current.
enum DRV8305_CTRL05_PeakSourTime_e { TSour_250_ns = (0 << 8), TSour_500_ns = (1 << 8), TSour_1000_ns = (2 << 8), TSour_2000_ns = (3 << 8) }
Enumeration for the high side and low side gate drive peak source time.
enum DRV8305_CTRL06_PeakSourCurLS_e {
ISour_LS_0p010_A = (0 << 0), ISour_LS_0p020_A = (1 << 0), ISour_LS_0p030_A = (2 << 0), ISour_LS_0p040_A = (3 << 0),
ISour_LS_0p050_A = (4 << 0), ISour_LS_0p060_A = (5 << 0), ISour_LS_0p070_A = (6 << 0), ISour_LS_0p125_A = (7 << 0),
ISour_LS_0p250_A = (8 << 0), ISour_LS_0p500_A = (9 << 0), ISour_LS_0p750_A = (10 << 0), ISour_LS_1p000_A = (11 << 0)
}
Enumeration for the low side gate drive peak source current.
enum DRV8305_CTRL06_PeakSinkCurLS_e {
ISink_LS_0p020_A = (0 << 4), ISink_LS_0p030_A = (1 << 4), ISink_LS_0p040_A = (2 << 4), ISink_LS_0p050_A = (3 << 4),
ISink_LS_0p060_A = (4 << 4), ISink_LS_0p070_A = (5 << 4), ISink_LS_0p125_A = (6 << 4), ISink_LS_0p250_A = (7 << 4),
ISink_LS_0p500_A = (8 << 4), ISink_LS_0p750_A = (9 << 4), ISink_LS_1p000_A = (10 << 4), ISink_LS_1p250_A = (11 << 4)
}
Enumeration for the low side gate drive peak sink current.
enum DRV8305_CTRL06_PeakSinkTime_e { TSink_250_ns = (0 << 8), TSink_500_ns = (1 << 8), TSink_1000_ns = (2 << 8), TSink_2000_ns = (3 << 8) }
Enumeration for the high side and low side gate drive peak sink time.
enum DRV8305_CTRL07_VDSDeglitch_e { VDSDeg_0_us = (0 << 0), VDSDeg_2_us = (1 << 0), VDSDeg_4_us = (2 << 0), VDSDeg_8_us = (3 << 0) }
Enumeration for the VDS sense deglitch time.
enum DRV8305_CTRL07_VDSBlanking_e { VDSBlnk_0_us = (0 << 2), VDSBlnk_2_us = (1 << 2), VDSBlnk_4_us = (2 << 2), VDSBlnk_8_us = (3 << 2) }
Enumeration for the VDS sense blanking time.
enum DRV8305_CTRL07_DeadTime_e {
DeadTime_40_ns = (0 << 4), DeadTime_60_ns = (1 << 4), DeadTime_100_ns = (2 << 4), DeadTime_500_ns = (3 << 4),
DeadTime_1000_ns = (4 << 4), DeadTime_2000_ns = (5 << 4), DeadTime_4000_ns = (6 << 4), DeadTime_6000_ns = (7 << 4)
}
Enumeration for the driver dead time.
enum DRV8305_CTRL07_PwmMode_e { PwmMode_6 = (0 << 7), PwmMode_3 = (1 << 7), PwmMode_1 = (2 << 7) }
Enumeration for the driver PWM mode.
enum DRV8305_CTRL07_CommOption_e { Diod = (0 << 9), Actv = (1 << 9) }
Enumeration for the driver commutation mode in 1 input.
enum DRV8305_CTRL09_WatchDelay_e { WD_Dly_10_ms = (0 << 5), WD_Dly_20_ms = (1 << 5), WD_Dly_50_ms = (2 << 5), WD_Dly_100_ms = (3 << 5) }
Enumeration for the IC's watchdog timer.
enum DRV8305_CTRL0A_CSGain1_e { Gain1_10VpV = (0 << 0), Gain1_20VpV = (1 << 0), Gain1_40VpV = (2 << 0), Gain1_80VpV = (3 << 0) }
Enumeration for the gain of shunt amplifier 1.
enum DRV8305_CTRL0A_CSGain2_e { Gain2_10VpV = (0 << 2), Gain2_20VpV = (1 << 2), Gain2_40VpV = (2 << 2), Gain2_80VpV = (3 << 2) }
Enumeration for the gain of shunt amplifier 2.
enum DRV8305_CTRL0A_CSGain3_e { Gain3_10VpV = (0 << 4), Gain3_20VpV = (1 << 4), Gain3_40VpV = (2 << 4), Gain3_80VpV = (3 << 4) }
Enumeration for the gain of shunt amplifier 3.
enum DRV8305_CTRL0A_CSBlank_e { Blank_0p00_us = (0 << 6), Blank_0p50_us = (1 << 6), Blank_2p50_us = (2 << 6), Blank_10p0_us = (3 << 6) }
Enumeration for the blanking time of the shunt amplifiers.
enum DRV8305_CTRL0A_DcCalMode_e {
DcCalMode_Ch1_Load = (0 << 8), DcCalMode_Ch1_NoLoad = (1 << 8), DcCalMode_Ch2_Load = (0 << 9), DcCalMode_Ch2_NoLoad = (1 << 9),
DcCalMode_Ch3_Load = (0 << 10), DcCalMode_Ch3_NoLoad = (1 << 10)
}
Enumeration for the DC calibration modes.
enum DRV8305_CTRL0B_VregUvLevel_e { UvLevel_10 = (0 << 0), UvLevel_20 = (1 << 0), UvLevel_30 = (2 << 0) }
Enumeration for the VREG under voltage level.
enum DRV8305_CTRL0B_SleepDelay_e { SleepDly_0_us = (0 << 3), SleepDly_10_us = (1 << 3), SleepDly_50_us = (2 << 3), SleepDly_1_ms = (3 << 3) }
Enumeration for the delay to power down VREG after SLEEP.
enum DRV8305_CTRL0B_VrefScaling_e { Scaling_k_1 = (0 << 8), Scaling_k_2 = (1 << 8), Scaling_k_4 = (2 << 8) }
Enumeration for the VREF scaling factor.
enum DRV8305_CTRL0C_VDSMode_e { Latched_Shutdown = (0 << 0), Report_Only = (1 << 0), Disable_VDS = (2 << 0) }
Enumeration for the VDS report mode.
enum DRV8305_CTRL0C_VDSLevel_e {
VDS_Level_0p060_V = (0 << 3), VDS_Level_0p068_V = (1 << 3), VDS_Level_0p076_V = (2 << 3), VDS_Level_0p086_V = (3 << 3),
VDS_Level_0p097_V = (4 << 3), VDS_Level_0p109_V = (5 << 3), VDS_Level_0p123_V = (6 << 3), VDS_Level_0p138_V = (7 << 3),
VDS_Level_0p155_V = (8 << 3), VDS_Level_0p175_V = (9 << 3), VDS_Level_0p197_V = (10 << 3), VDS_Level_0p222_V = (11 << 3),
VDS_Level_0p250_V = (12 << 3), VDS_Level_0p282_V = (13 << 3), VDS_Level_0p317_V = (14 << 3), VDS_Level_0p358_V = (15 << 3),
VDS_Level_0p403_V = (16 << 3), VDS_Level_0p454_V = (17 << 3), VDS_Level_0p511_V = (18 << 3), VDS_Level_0p576_V = (19 << 3),
VDS_Level_0p648_V = (20 << 3), VDS_Level_0p730_V = (21 << 3), VDS_Level_0p822_V = (22 << 3), VDS_Level_0p926_V = (23 << 3),
VDS_Level_1p043_V = (24 << 3), VDS_Level_1p175_V = (25 << 3), VDS_Level_1p324_V = (26 << 3), VDS_Level_1p491_V = (27 << 3),
VDS_Level_1p679_V = (28 << 3), VDS_Level_1p892_V = (29 << 3), VDS_Level_2p131_V = (30 << 3)
}
Enumeration for the VDS comparator threshold.
enum DRV8305_Address_e {
Address_Status_1 = 1 << 11, Address_Status_2 = 2 << 11, Address_Status_3 = 3 << 11, Address_Status_4 = 4 << 11,
Address_Control_5 = 5 << 11, Address_Control_6 = 6 << 11, Address_Control_7 = 7 << 11, Address_Control_8 = 8 << 11,
Address_Control_9 = 9 << 11, Address_Control_A = 10 << 11, Address_Control_B = 11 << 11, Address_Control_C = 12 << 11
}
Enumeration for the register addresses.
enum DRV8305_ShuntAmpNumber_e { ShuntAmpNumber_1 = 1, ShuntAmpNumber_2 = 2, ShuntAmpNumber_3 = 3 }
Enumeration for the shunt amplifier number.
Functions
DRV8305_Handle DRV8305_init (void *pMemory, const size_t numBytes)
Initializes the DRV8305 object.
static DRV8305_Word_t DRV8305_buildCtrlWord (const DRV8305_CtrlMode_e ctrlMode, const DRV8305_Address_e regAddr, const uint16_t data)
Builds the control word.
void DRV8305_enable (DRV8305_Handle handle)
Enables the DRV8305.
DRV8305_CTRL05_PeakSourCurHS_e DRV8305_getPeakSourCurHS (DRV8305_Handle handle)
Gets the high side gate drive peak source current level.
DRV8305_CTRL05_PeakSinkCurHS_e DRV8305_getPeakSinkCurHS (DRV8305_Handle handle)
Gets the high side gate drive peak sink current level.
DRV8305_CTRL05_PeakSourTime_e DRV8305_getPeakSourTime (DRV8305_Handle handle)
Gets the high side and low side gate drive peak source time.
DRV8305_CTRL06_PeakSourCurLS_e DRV8305_getPeakSourCurLS (DRV8305_Handle handle)
Gets the low side gate drive peak source current level.
DRV8305_CTRL06_PeakSinkCurLS_e DRV8305_getPeakSinkCurLS (DRV8305_Handle handle)
Gets the low side side gate drive peak sink current level.
DRV8305_CTRL06_PeakSinkTime_e DRV8305_getPeakSinkTime (DRV8305_Handle handle)
Gets the high side and low side gate drive peak sink time.
DRV8305_CTRL07_VDSDeglitch_e DRV8305_getVDSDeglitch (DRV8305_Handle handle)
Gets the VDS sense deglitch time.
DRV8305_CTRL07_VDSBlanking_e DRV8305_getVDSBlanking (DRV8305_Handle handle)
Gets the VDS sense blanking time.
DRV8305_CTRL07_DeadTime_e DRV8305_getDeadTime (DRV8305_Handle handle)
Gets the driver dead time.
DRV8305_CTRL07_PwmMode_e DRV8305_getPwmMode (DRV8305_Handle handle)
Gets the driver PWM mode.
DRV8305_CTRL07_CommOption_e DRV8305_getCommOption (DRV8305_Handle handle)
Gets the driver commutation mode for 1PWM mode.
DRV8305_CTRL09_WatchDelay_e DRV8305_getWatchDelay (DRV8305_Handle handle)
Gets the watchdog timer setting.
DRV8305_CTRL0A_CSGain1_e DRV8305_getCSGain1 (DRV8305_Handle handle)
Gets the gain of shunt amplifier 1.
DRV8305_CTRL0A_CSGain2_e DRV8305_getCSGain2 (DRV8305_Handle handle)
Gets the gain of shunt amplifier 2.
DRV8305_CTRL0A_CSGain3_e DRV8305_getCSGain3 (DRV8305_Handle handle)
Gets the gain of shunt amplifier 3.
DRV8305_CTRL0A_CSBlank_e DRV8305_getCSBlank (DRV8305_Handle handle)
Gets the blanking time of the shunt amplifiers.
DRV8305_CTRL0A_DcCalMode_e DRV8305_getDcCalMode (DRV8305_Handle handle, const DRV8305_ShuntAmpNumber_e ampNumber)
Gets the DC calibration mode.
DRV8305_CTRL0B_VregUvLevel_e DRV8305_getVregUvLevel (DRV8305_Handle handle)
Gets the under voltage level of VREF.
DRV8305_CTRL0B_SleepDelay_e DRV8305_getSleepDelay (DRV8305_Handle handle)
Gets the delay time to power down VREF after SLEEP.
DRV8305_CTRL0B_VrefScaling_e DRV8305_getVrefScaling (DRV8305_Handle handle)
Gets the VREF scaling factor.
DRV8305_CTRL0C_VDSMode_e DRV8305_getVDSMode (DRV8305_Handle handle)
Gets the VDS protection mode.
DRV8305_CTRL0C_VDSLevel_e DRV8305_getVDSLevel (DRV8305_Handle handle)
Gets the VDS OC level.
void DRV8305_setSpiHandle (DRV8305_Handle handle, SPI_Handle spiHandle)
Sets the SPI handle in the DRV8305.
void DRV8305_setGpioHandle (DRV8305_Handle handle, GPIO_Handle gpioHandle)
Sets the GPIO handle in the DRV8305.
void DRV8305_setGpioNumber (DRV8305_Handle handle, GPIO_Number_e gpioNumber)
Sets the GPIO number in the DRV8305.
void DRV8305_setPeakSourCurHS (DRV8305_Handle handle, const DRV8305_CTRL05_PeakSourCurHS_e level)
Sets the high side gate drive peak source current level.
void DRV8305_setPeakSinkCurHS (DRV8305_Handle handle, const DRV8305_CTRL05_PeakSinkCurHS_e level)
Sets the high side gate drive peak sink current level.
void DRV8305_setPeakSourTime (DRV8305_Handle handle, const DRV8305_CTRL05_PeakSourTime_e time)
Sets the high side and low side gate drive peak source time.
void DRV8305_setPeakSourCurLS (DRV8305_Handle handle, const DRV8305_CTRL06_PeakSourCurLS_e level)
Sets the the low side gate drive peak source current level.
void DRV8305_setPeakSinkCurLS (DRV8305_Handle handle, const DRV8305_CTRL06_PeakSinkCurLS_e level)
Sets the low side side gate drive peak sink current level.
void DRV8305_setPeakSinkTime (DRV8305_Handle handle, const DRV8305_CTRL06_PeakSinkTime_e time)
Sets the high side and low side gate drive peak sink time.
void DRV8305_setVDSDeglitch (DRV8305_Handle handle, const DRV8305_CTRL07_VDSDeglitch_e time)
Sets the VDS sense deglitch time.
void DRV8305_setVDSBlanking (DRV8305_Handle handle, const DRV8305_CTRL07_VDSBlanking_e time)
Sets the VDS sense blanking time.
void DRV8305_setDeadTime (DRV8305_Handle handle, const DRV8305_CTRL07_DeadTime_e time)
Sets the driver dead time.
void DRV8305_setPwmMode (DRV8305_Handle handle, const DRV8305_CTRL07_PwmMode_e mode)
Sets the driver PWM mode.
void DRV8305_setCommOption (DRV8305_Handle handle, const DRV8305_CTRL07_CommOption_e mode)
Sets the driver commutation mode for 1PWM mode.
void DRV8305_setWatchDelay (DRV8305_Handle handle, const DRV8305_CTRL09_WatchDelay_e time)
Sets the watchdog timer setting.
void DRV8305_setCSGain1 (DRV8305_Handle handle, const DRV8305_CTRL0A_CSGain1_e gain)
Sets the gain of shunt amplifier 1.
void DRV8305_setCSGain2 (DRV8305_Handle handle, const DRV8305_CTRL0A_CSGain2_e gain)
Sets the gain of shunt amplifier 2.
void DRV8305_setCSGain3 (DRV8305_Handle handle, const DRV8305_CTRL0A_CSGain3_e gain)
Sets the gain of shunt amplifier 3.
void DRV8305_setCSBlank (DRV8305_Handle handle, const DRV8305_CTRL0A_CSBlank_e time)
Sets the blanking time of the shunt amplifiers.
void DRV8305_setDcCalMode (DRV8305_Handle handle, const DRV8305_ShuntAmpNumber_e ampNumber, const DRV8305_CTRL0A_DcCalMode_e mode)
Sets the DC calibration mode.
void DRV8305_setVregUvLevel (DRV8305_Handle handle, const DRV8305_CTRL0B_VregUvLevel_e level)
Sets the under voltage level of VREF.
void DRV8305_setSleepDelay (DRV8305_Handle handle, const DRV8305_CTRL0B_SleepDelay_e time)
Sets the delay time to power down VREF after SLEEP.
void DRV8305_setVrefScaling (DRV8305_Handle handle, const DRV8305_CTRL0B_VrefScaling_e mode)
Sets the VREF scaling factor.
void DRV8305_setVDSMode (DRV8305_Handle handle, const DRV8305_CTRL0C_VDSMode_e mode)
Sets the VDS protection mode.
void DRV8305_setVDSLevel (DRV8305_Handle handle, const DRV8305_CTRL0C_VDSLevel_e level)
Sets the VDS OC level.
bool DRV8305_isFault (DRV8305_Handle handle)
Determines if DRV8305 fault has occurred.
void DRV8305_reset (DRV8305_Handle handle)
Resets the DRV8305.
static void DRV8305_resetEnableTimeout (DRV8305_Handle handle)
Resets the enable timeout flag.
static void DRV8305_resetRxTimeout (DRV8305_Handle handle)
Resets the RX fifo timeout flag.
void DRV8305_setupSpi (DRV8305_Handle handle, DRV_SPI_8305_Vars_t *Spi_8305_Vars)
Initialize the interface to all 8305 SPI variables.
uint16_t DRV8305_readSpi (DRV8305_Handle handle, const DRV8305_Address_e regAddr)
Reads data from the DRV8305 register.
void DRV8305_writeSpi (DRV8305_Handle handle, const DRV8305_Address_e regAddr, const uint16_t data)
Writes data to the DRV8305 register.
void DRV8305_writeData (DRV8305_Handle handle, DRV_SPI_8305_Vars_t *Spi_8305_Vars)
Write to the DRV8305 SPI registers.
void DRV8305_readData (DRV8305_Handle handle, DRV_SPI_8305_Vars_t *Spi_8305_Vars)
Read from the DRV8305 SPI registers.
Detailed Description
Data Structure Documentation
struct _DRV_SPI_8305_Stat01_t_
Object for the DRV8305 STATUS01 register.
Definition at line 878 of file drv8305.h.
Data Fields
bool FAULT
bool OTW
bool PVDD_OVFL
bool PVDD_UVFL
bool STAT01_RSV1
bool TEMP_FLAG1
bool TEMP_FLAG2
bool TEMP_FLAG3
bool TEMP_FLAG4
bool VCPH_UVFL
bool VDS_STATUS
struct _DRV_SPI_8305_Stat02_t_
Object for the DRV8305 STATUS02 register.
Definition at line 896 of file drv8305.h.
Data Fields
bool FETHA_VDS
bool FETHB_VDS
bool FETHC_VDS
bool FETLA_VDS
bool FETLB_VDS
bool FETLC_VDS
bool SNS_A_OCP
bool SNS_B_OCP
bool SNS_C_OCP
bool STAT02_RSV1
bool STAT02_RSV2
struct _DRV_SPI_8305_Stat03_t_
Object for the DRV8305 STATUS03 register.
Definition at line 914 of file drv8305.h.
Data Fields
bool AVDD_UVLO
bool OTS
bool PVDD_UVLO2
bool STAT03_RSV1
bool STAT03_RSV2
bool VCP_LSD_UVLO2
bool VCPH_OVLO
bool VCPH_OVLO_ABS
bool VCPH_UVLO2
bool VREG_UV
bool WD_FAULT
struct _DRV_SPI_8305_Stat04_t_
Object for the DRV8305 STATUS04 register.
Definition at line 932 of file drv8305.h.
Data Fields
bool FETHA_VGS
bool FETHB_VGS
bool FETHC_VGS
bool FETLA_VGS
bool FETLB_VGS
bool FETLC_VGS
bool STAT04_RSV1
bool STAT04_RSV2
bool STAT04_RSV3
bool STAT04_RSV4
bool STAT04_RSV5
struct _DRV_SPI_8305_Ctrl05_t_
Object for the DRV8305 CTRL05 register.
Definition at line 950 of file drv8305.h.
Data Fields
bool CTRL05_RSV1
DRV8305_CTRL05_PeakSinkCurHS_e IDRIVEN_HS
DRV8305_CTRL05_PeakSourCurHS_e IDRIVEP_HS
DRV8305_CTRL05_PeakSourTime_e TDRIVEN
struct _DRV_SPI_8305_Ctrl06_t_
Object for the DRV8305 CTRL06 register.
Definition at line 961 of file drv8305.h.
Data Fields
bool CTRL06_RSV1
DRV8305_CTRL06_PeakSinkCurLS_e IDRIVEN_LS
DRV8305_CTRL06_PeakSourCurLS_e IDRIVEP_LS
DRV8305_CTRL06_PeakSinkTime_e TDRIVEP
struct _DRV_SPI_8305_Ctrl07_t_
Object for the DRV8305 CTRL07 register.
Definition at line 972 of file drv8305.h.
Data Fields
DRV8305_CTRL07_CommOption_e COMM_OPT
bool CTRL07_RSV1
DRV8305_CTRL07_DeadTime_e DEAD_TIME
DRV8305_CTRL07_PwmMode_e PWM_MODE
DRV8305_CTRL07_VDSBlanking_e TBLANK
DRV8305_CTRL07_VDSDeglitch_e TVDS
struct _DRV_SPI_8305_Ctrl08_t_
Object for the DRV8305 CTRL08 register.
Definition at line 985 of file drv8305.h.
Data Fields
uint16_t CTRL08_RSV1
struct _DRV_SPI_8305_Ctrl09_t_
Object for the DRV8305 CTRL09 register.
Definition at line 993 of file drv8305.h.
Data Fields
bool CLR_FLTS
bool DIS_GDRV_FAULT
bool DIS_SNS_OCP
bool DISABLE
bool EN_SNS_CLAMP
bool FLIP_OTS
bool SET_VCPH_UV
bool SLEEP
DRV8305_CTRL09_WatchDelay_e WD_DLY
bool WD_EN
struct _DRV_SPI_8305_Ctrl0A_t_
Object for the DRV8305 CTRL0A register.
Definition at line 1010 of file drv8305.h.
Data Fields
DRV8305_CTRL0A_CSBlank_e CS_BLANK
bool DC_CAL_CH1
bool DC_CAL_CH2
bool DC_CAL_CH3
DRV8305_CTRL0A_CSGain1_e GAIN_CS1
DRV8305_CTRL0A_CSGain2_e GAIN_CS2
DRV8305_CTRL0A_CSGain3_e GAIN_CS3
struct _DRV_SPI_8305_Ctrl0B_t_
Object for the DRV8305 CTRL0B register.
Definition at line 1024 of file drv8305.h.
Data Fields
bool CTRL0B_RSV1
bool CTRL0B_RSV2
bool CTRL0B_RSV3
bool CTRL0B_RSV4
bool DIS_PWRGD
DRV8305_CTRL0B_SleepDelay_e SLP_DLY
DRV8305_CTRL0B_VrefScaling_e VREF_SCALING
DRV8305_CTRL0B_VregUvLevel_e VREG_UV_LEVEL
struct _DRV_SPI_8305_Ctrl0C_t_
Object for the DRV8305 CTRL0C register.
Definition at line 1039 of file drv8305.h.
Data Fields
bool CTRL0C_RSV1
bool CTRL0C_RSV2
bool CTRL0C_RSV3
DRV8305_CTRL0C_VDSLevel_e VDS_LEVEL
DRV8305_CTRL0C_VDSMode_e VDS_MODE
struct _DRV_SPI_8305_Vars_t_
Object for the DRV8305 registers and commands.
Definition at line 1051 of file drv8305.h.
Data Fields
DRV_SPI_8305_Ctrl05_t_ Ctrl_Reg_05
DRV_SPI_8305_Ctrl06_t_ Ctrl_Reg_06
DRV_SPI_8305_Ctrl07_t_ Ctrl_Reg_07
DRV_SPI_8305_Ctrl08_t_ Ctrl_Reg_08
DRV_SPI_8305_Ctrl09_t_ Ctrl_Reg_09
DRV_SPI_8305_Ctrl0A_t_ Ctrl_Reg_0A
DRV_SPI_8305_Ctrl0B_t_ Ctrl_Reg_0B
DRV_SPI_8305_Ctrl0C_t_ Ctrl_Reg_0C
uint16_t ManReadAddr
bool ManReadCmd
uint16_t ManReadData
uint16_t ManWriteAddr
bool ManWriteCmd
uint16_t ManWriteData
bool ReadCmd
DRV_SPI_8305_Stat01_t_ Stat_Reg_01
DRV_SPI_8305_Stat02_t_ Stat_Reg_02
DRV_SPI_8305_Stat03_t_ Stat_Reg_03
DRV_SPI_8305_Stat04_t_ Stat_Reg_04
bool WriteCmd
struct _DRV8305_Obj_
Defines the DRV8305 object.
Definition at line 1080 of file drv8305.h.
Data Fields
bool enableTimeOut the timeout flag for drv8305 enable
GPIO_Handle gpioHandle the gpio handle that is connected to the drv8305 enable pin
GPIO_Number_e gpioNumber the gpio number that is connected to the drv8305 enable pin
bool RxTimeOut the timeout flag for the RX fifo
SPI_Handle spiHandle the handle for the serial peripheral interface
Macro Definition Documentation
#define DRV8305_ADDR_MASK (0x7800)
Defines the address mask.
Definition at line 76 of file drv8305.h.
#define DRV8305_CTRL05_IDRIVEN_HS_BITS (15 << 4)
Defines the location of the IDRIVEN_HS bits in the Control 5 register.
Definition at line 280 of file drv8305.h.
Referenced by DRV8305_getPeakSinkCurHS(), DRV8305_readData(), DRV8305_setPeakSinkCurHS(), and DRV8305_setupSpi().
#define DRV8305_CTRL05_IDRIVEP_HS_BITS (15 << 0)
Defines the location of the IDRIVEP_HS bits in the Control 5 register.
Definition at line 276 of file drv8305.h.
Referenced by DRV8305_getPeakSourCurHS(), DRV8305_readData(), DRV8305_setPeakSourCurHS(), and DRV8305_setupSpi().
#define DRV8305_CTRL05_RESERVED1_BITS (1 << 10)
Defines the location of the RESERVED1 bits in the Control 5 register.
Definition at line 288 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL05_TDRIVEN_BITS (3 << 8)
Defines the location of the TDRIVEN bits in the Control 5 register.
Definition at line 284 of file drv8305.h.
Referenced by DRV8305_getPeakSourTime(), DRV8305_readData(), DRV8305_setPeakSourTime(), and DRV8305_setupSpi().
#define DRV8305_CTRL06_IDRIVEN_LS_BITS (15 << 4)
Defines the location of the IDRIVEN_LS bits in the Control 6 register.
Definition at line 297 of file drv8305.h.
Referenced by DRV8305_getPeakSinkCurLS(), DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL06_IDRIVEP_LS_BITS (15 << 0)
Defines the location of the IDRIVEP_LS bits in the Control 6 register.
Definition at line 293 of file drv8305.h.
Referenced by DRV8305_getPeakSourCurLS(), DRV8305_readData(), DRV8305_setPeakSinkCurLS(), and DRV8305_setupSpi().
#define DRV8305_CTRL06_RESERVED1_BITS (1 << 10)
Defines the location of the RESERVED1 bits in the Control 6 register.
Definition at line 305 of file drv8305.h.
#define DRV8305_CTRL06_TDRIVEP_BITS (3 << 8)
Defines the location of the TDRIVEP bits in the Control 6 register.
Definition at line 301 of file drv8305.h.
Referenced by DRV8305_getPeakSinkTime(), DRV8305_readData(), DRV8305_setPeakSinkTime(), and DRV8305_setupSpi().
#define DRV8305_CTRL07_COMM_OPT_BITS (1 << 9)
Defines the location of the COMM_OPT bits in the Control 7 register.
Definition at line 326 of file drv8305.h.
Referenced by DRV8305_getCommOption(), DRV8305_readData(), DRV8305_setCommOption(), and DRV8305_setupSpi().
#define DRV8305_CTRL07_DEAD_TIME_BITS (7 << 4)
Defines the location of the DEAD_TIME bits in the Control 7 register.
Definition at line 318 of file drv8305.h.
Referenced by DRV8305_getDeadTime(), DRV8305_readData(), DRV8305_setDeadTime(), and DRV8305_setupSpi().
#define DRV8305_CTRL07_PWM_MODE_BITS (3 << 7)
Defines the location of the PWM_MODE bits in the Control 7 register.
Definition at line 322 of file drv8305.h.
Referenced by DRV8305_getPwmMode(), DRV8305_readData(), DRV8305_setPwmMode(), and DRV8305_setupSpi().
#define DRV8305_CTRL07_RESERVED1_BITS (1 << 10)
Defines the location of the RESERVED1 bits in the Control 7 register.
Definition at line 330 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL07_TBLANK_BITS (3 << 2)
Defines the location of the TBLANK bits in the Control 7 register.
Definition at line 314 of file drv8305.h.
Referenced by DRV8305_getVDSBlanking(), DRV8305_readData(), DRV8305_setupSpi(), and DRV8305_setVDSBlanking().
#define DRV8305_CTRL07_TVDS_BITS (3 << 0)
Defines the location of the TVDS bits in the Control 7 register.
Definition at line 310 of file drv8305.h.
Referenced by DRV8305_getVDSDeglitch(), DRV8305_readData(), DRV8305_setupSpi(), and DRV8305_setVDSDeglitch().
#define DRV8305_CTRL08_RESERVED_BITS (2047 << 0)
Defines the location of the RESERVED bits in the Control 8 register.
Definition at line 335 of file drv8305.h.
#define DRV8305_CTRL09_CLR_FLTS_BITS (1 << 1)
Defines the location of the CLR_FLTS bits in the Control 9 register.
Definition at line 344 of file drv8305.h.
Referenced by DRV8305_readData(), DRV8305_reset(), and DRV8305_setupSpi().
#define DRV8305_CTRL09_DIS_GDRV_FAULT_BITS (1 << 8)
Defines the location of the DIS_GDRV_FAULT bits in the Control 9 register.
Definition at line 368 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL09_DIS_SNS_OCP_BITS (1 << 4)
Defines the location of the DIS_SNS_OCP bits in the Control 9 register.
Definition at line 356 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL09_DISABLE_BITS (1 << 9)
Defines the location of the DISABLE bits in the Control 9 register.
Definition at line 372 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL09_EN_SNS_CLAMP_BITS (1 << 7)
Defines the location of the EN_SNS_CLAMP bits in the Control 9 register.
Definition at line 364 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL09_FLIP_OTS_BITS (1 << 10)
Defines the location of the FLIP_OTS bits in the Control 9 register.
Definition at line 376 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL09_SET_VCPH_UV_BITS (1 << 0)
Defines the location of the SET_VCPH_UV bits in the Control 9 register.
Definition at line 340 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL09_SLEEP_BITS (1 << 2)
Defines the location of the SLEEP bits in the Control 9 register.
Definition at line 348 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL09_WD_DLY_BITS (3 << 5)
Defines the location of the WD_DLY bits in the Control 9 register.
Definition at line 360 of file drv8305.h.
Referenced by DRV8305_getWatchDelay(), DRV8305_readData(), DRV8305_setupSpi(), and DRV8305_setWatchDelay().
#define DRV8305_CTRL09_WD_EN_BITS (1 << 3)
Defines the location of the WD_EN bits in the Control 9 register.
Definition at line 352 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL0A_CS_BLANK_BITS (3 << 6)
Defines the location of the CS_BLANK bits in the Control A register.
Definition at line 393 of file drv8305.h.
Referenced by DRV8305_getCSBlank(), DRV8305_readData(), DRV8305_setCSBlank(), and DRV8305_setupSpi().
#define DRV8305_CTRL0A_DC_CAL_CH1_BITS (1 << 8)
Defines the location of the DC_CAL_CH1 bits in the Control A register.
Definition at line 397 of file drv8305.h.
Referenced by DRV8305_getDcCalMode(), DRV8305_readData(), DRV8305_setDcCalMode(), and DRV8305_setupSpi().
#define DRV8305_CTRL0A_DC_CAL_CH2_BITS (1 << 9)
Defines the location of the DC_CAL_CH2 bits in the Control A register.
Definition at line 401 of file drv8305.h.
Referenced by DRV8305_getDcCalMode(), DRV8305_readData(), DRV8305_setDcCalMode(), and DRV8305_setupSpi().
#define DRV8305_CTRL0A_DC_CAL_CH3_BITS (1 << 10)
Defines the location of the DC_CAL_CH3 bits in the Control A register.
Definition at line 405 of file drv8305.h.
Referenced by DRV8305_getDcCalMode(), DRV8305_readData(), DRV8305_setDcCalMode(), and DRV8305_setupSpi().
#define DRV8305_CTRL0A_GAIN_CS1_BITS (3 << 0)
Defines the location of the GAIN_CS1 bits in the Control A register.
Definition at line 381 of file drv8305.h.
Referenced by DRV8305_getCSGain1(), DRV8305_readData(), DRV8305_setCSGain1(), and DRV8305_setupSpi().
#define DRV8305_CTRL0A_GAIN_CS2_BITS (3 << 2)
Defines the location of the GAIN_CS2 bits in the Control A register.
Definition at line 385 of file drv8305.h.
Referenced by DRV8305_getCSGain2(), DRV8305_readData(), DRV8305_setCSGain2(), and DRV8305_setupSpi().
#define DRV8305_CTRL0A_GAIN_CS3_BITS (3 << 4)
Defines the location of the GAIN_CS3 bits in the Control A register.
Definition at line 389 of file drv8305.h.
Referenced by DRV8305_getCSGain3(), DRV8305_readData(), DRV8305_setCSGain3(), and DRV8305_setupSpi().
#define DRV8305_CTRL0B_DIS_PWRGD_BITS (1 << 2)
Defines the location of the DIS_PWRGD bits in the Control B register.
Definition at line 414 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL0B_RESERVED1_BITS (1 << 5)
Defines the location of the RESERVED1 bits in the Control B register.
Definition at line 422 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL0B_RESERVED2_BITS (1 << 6)
Defines the location of the RESERVED2 bits in the Control B register.
Definition at line 426 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL0B_RESERVED3_BITS (1 << 7)
Defines the location of the RESERVED3 bits in the Control B register.
Definition at line 430 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL0B_RESERVED4_BITS (1 << 10)
Defines the location of the RESERVED4 bits in the Control B register.
Definition at line 438 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL0B_SLP_DLY_BITS (3 << 3)
Defines the location of the SLP_DLY bits in the Control B register.
Definition at line 418 of file drv8305.h.
Referenced by DRV8305_getSleepDelay(), DRV8305_readData(), DRV8305_setSleepDelay(), and DRV8305_setupSpi().
#define DRV8305_CTRL0B_VREF_SCALING_BITS (3 << 8)
Defines the location of the VREF_SCALING bits in the Control B register.
Definition at line 434 of file drv8305.h.
Referenced by DRV8305_getVrefScaling(), DRV8305_readData(), DRV8305_setupSpi(), and DRV8305_setVrefScaling().
#define DRV8305_CTRL0B_VREG_UV_LEVEL_BITS (3 << 0)
Defines the location of the VREG_UV_LEVEL bits in the Control B register.
Definition at line 410 of file drv8305.h.
Referenced by DRV8305_getVregUvLevel(), DRV8305_readData(), DRV8305_setupSpi(), and DRV8305_setVregUvLevel().
#define DRV8305_CTRL0C_RESERVED1_BITS (1 << 8)
Defines the location of the RESERVED1 bits in the Control B register.
Definition at line 451 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL0C_RESERVED2_BITS (1 << 9)
Defines the location of the RESERVED2 bits in the Control B register.
Definition at line 455 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL0C_RESERVED3_BITS (1 << 10)
Defines the location of the RESERVED3 bits in the Control B register.
Definition at line 459 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_CTRL0C_VDS_LEVEL_BITS (31 << 3)
Defines the location of the VDS_LEVEL bits in the Control B register.
Definition at line 447 of file drv8305.h.
Referenced by DRV8305_getVDSLevel(), DRV8305_readData(), DRV8305_setupSpi(), and DRV8305_setVDSLevel().
#define DRV8305_CTRL0C_VDS_MODE_BITS (7 << 0)
Defines the location of the VDS_MODE bits in the Control B register.
Definition at line 443 of file drv8305.h.
Referenced by DRV8305_getVDSMode(), DRV8305_readData(), DRV8305_setupSpi(), and DRV8305_setVDSMode().
#define DRV8305_DATA_MASK (0x07FF)
Defines the data mask.
Definition at line 81 of file drv8305.h.
Referenced by DRV8305_buildCtrlWord(), and DRV8305_readSpi().
#define DRV8305_FAULT_TYPE_MASK (0x07FF)
Defines the R/W mask.
Definition at line 91 of file drv8305.h.
#define DRV8305_RW_MASK (0x8000)
Defines the R/W mask.
Definition at line 86 of file drv8305.h.
#define DRV8305_STATUS01_FAULT_BITS (1 << 10)
Defines the location of the FAULT (0-Warning, 1-Latched) bits in the Status 1 register.
Definition at line 136 of file drv8305.h.
Referenced by DRV8305_enable(), DRV8305_isFault(), DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_OTW_BITS (1 << 0)
Defines the location of the OTW (Over temperature warning) bits in the Status 1 register.
Definition at line 96 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_PVDD_OVFL_BITS (1 << 6)
Defines the location of the PVDD_OVFL (PVDD over voltage) bits in the Status 1 register.
Definition at line 120 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_PVDD_UVFL_BITS (1 << 7)
Defines the location of the PVDD_UVFL (PVDD under voltage) bits in the Status 1 register.
Definition at line 124 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_RESERVED1_BITS (1 << 9)
Defines the location of the RESERVED1 bits in the Status 1 register.
Definition at line 132 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_TEMP_FLAG1_BITS (1 << 3)
Defines the location of the TEMP_FLAG1 (Over temperature warning 1) bits in the Status 1 register.
Definition at line 108 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_TEMP_FLAG2_BITS (1 << 2)
Defines the location of the TEMP_FLAG2 (Over temperature warning 2) bits in the Status 1 register.
Definition at line 104 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_TEMP_FLAG3_BITS (1 << 1)
Defines the location of the TEMP_FLAG3 (Over temperature warning 3) bits in the Status 1 register.
Definition at line 100 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_TEMP_FLAG4_BITS (1 << 8)
Defines the location of the TEMP_FLAG4 (Over temperature warning 4) bits in the Status 1 register.
Definition at line 128 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_VCPH_UVFL_BITS (1 << 4)
Defines the location of the VCPH_UVFL (Charge pump high, under voltage) bits in the Status 1 register.
Definition at line 112 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS01_VDS_STATUS_BITS (1 << 5)
Defines the location of the VDS_STATUS (Real time "OR" of 0x02[D5:D10]) bits in the Status 1 register.
Definition at line 116 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_FETHA_VDS_BITS (1 << 10)
Defines the location of the FETHA_VDS (A high side, VDS Fault) bits in the Status 2 register.
Definition at line 181 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_FETHB_VDS_BITS (1 << 8)
Defines the location of the FETHB_VDS (B high side, VDS Fault) bits in the Status 2 register.
Definition at line 173 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_FETHC_VDS_BITS (1 << 6)
Defines the location of the FETHC_VDS (C high side, VDS Fault) bits in the Status 2 register.
Definition at line 165 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_FETLA_VDS_BITS (1 << 9)
Defines the location of the FETLA_VDS (A low side, VDS Fault) bits in the Status 2 register.
Definition at line 177 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_FETLB_VDS_BITS (1 << 7)
Defines the location of the FETLB_VDS (B low side, VDS Fault) bits in the Status 2 register.
Definition at line 169 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_FETLC_VDS_BITS (1 << 5)
Defines the location of the FETLC_VDS (C low side, VDS Fault) bits in the Status 2 register.
Definition at line 161 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_RESERVED1_BITS (1 << 3)
Defines the location of the RESERVED1 bits in the Status 2 register.
Definition at line 153 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_RESERVED2_BITS (1 << 4)
Defines the location of the RESERVED2 bits in the Status 2 register.
Definition at line 157 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_SNS_A_OCP_BITS (1 << 0)
Defines the location of the SNS_A_OCP (Sense amp A over current) bits in the Status 2 register.
Definition at line 141 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_SNS_B_OCP_BITS (1 << 1)
Defines the location of the SNS_B_OCP (Sense amp B over current) bits in the Status 2 register.
Definition at line 145 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS02_SNS_C_OCP_BITS (1 << 2)
Defines the location of the SNS_C_OCP (Sense amp C over current) bits in the Status 2 register.
Definition at line 149 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_AVDD_UVLO_BITS (1 << 5)
Defines the location of the AVDD_UVLO (AVDD regulator under voltage) bits in the Status 3 register.
Definition at line 206 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_OTS_BITS (1 << 8)
Defines the location of the OTS (Over temperature shut down) bits in the Status 3 register.
Definition at line 218 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_PVDD_UVLO2_BITS (1 << 10)
Defines the location of the PVDD_UVLO2 (PVDD under voltage 2) bits in the Status 3 register.
Definition at line 226 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_RESERVED1_BITS (1 << 3)
Defines the location of the RESERVED1 bits in the Status 3 register.
Definition at line 198 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_RESERVED2_BITS (1 << 7)
Defines the location of the RESERVED2 bits in the Status 3 register.
Definition at line 214 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_VCP_LSD_UVLO2_BITS (1 << 4)
Defines the location of the VCP_LSD_UVLO2 (Charge pump low, under voltage 2) bits in the Status 3 register.
Definition at line 202 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_VCPH_OVLO_ABS_BITS (1 << 0)
Defines the location of the VCPH_OVLO_ABS (Charge pump high, absolute over voltage) bits in the Status 3 register.
Definition at line 186 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_VCPH_OVLO_BITS (1 << 1)
Defines the location of the VCPH_OVLO (Charge pump high, over voltage) bits in the Status 3 register.
Definition at line 190 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_VCPH_UVLO2_BITS (1 << 2)
Defines the location of the VCPH_UVLO2 (Charge pump high, under voltage 2) bits in the Status 3 register.
Definition at line 194 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_VREG_UV_BITS (1 << 6)
Defines the location of the VREG_UV (VREG regulator under voltage) bits in the Status 3 register.
Definition at line 210 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS03_WD_FAULT_BITS (1 << 9)
Defines the location of the WD_FAULT (Watchdog fault) bits in the Status 3 register.
Definition at line 222 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_FETHA_VGS_BITS (1 << 10)
Defines the location of the FETHA_VGS (A high side, VGS Fault) bits in the Status 4 register.
Definition at line 271 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_FETHB_VGS_BITS (1 << 8)
Defines the location of the FETHB_VGS (B high side, VGS Fault) bits in the Status 4 register.
Definition at line 263 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_FETHC_VGS_BITS (1 << 6)
Defines the location of the FETHC_VGS (C high side, VGS Fault) bits in the Status 4 register.
Definition at line 255 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_FETLA_VGS_BITS (1 << 9)
Defines the location of the FETLA_VGS (A low side, VGS Fault) bits in the Status 4 register.
Definition at line 267 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_FETLB_VGS_BITS (1 << 7)
Defines the location of the FETLB_VGS (B low side, VGS Fault) bits in the Status 4 register.
Definition at line 259 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_FETLC_VGS_BITS (1 << 5)
Defines the location of the FETLC_VGS (C low side, VGS Fault) bits in the Status 4 register.
Definition at line 251 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_RESERVED1_BITS (1 << 0)
Defines the location of the RESERVED1 bits in the Status 4 register.
Definition at line 231 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_RESERVED2_BITS (1 << 1)
Defines the location of the RESERVED2 bits in the Status 4 register.
Definition at line 235 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_RESERVED3_BITS (1 << 2)
Defines the location of the RESERVED3 bits in the Status 4 register.
Definition at line 239 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_RESERVED4_BITS (1 << 3)
Defines the location of the RESERVED4 bits in the Status 4 register.
Definition at line 243 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
#define DRV8305_STATUS04_RESERVED5_BITS (1 << 4)
Defines the location of the RESERVED5 bits in the Status 4 register.
Definition at line 247 of file drv8305.h.
Referenced by DRV8305_readData(), and DRV8305_setupSpi().
Typedef Documentation
typedef struct _DRV8305_Obj_* DRV8305_Handle
Defines the DRV8305 handle.
Definition at line 1092 of file drv8305.h.
typedef struct _DRV8305_Obj_ DRV8305_Obj
Defines the DRV8305 object.
typedef uint16_t DRV8305_Word_t
Defines the DRV8305 Word type.
Definition at line 1097 of file drv8305.h.
typedef struct _DRV_SPI_8305_Ctrl05_t_ DRV_SPI_8305_Ctrl05_t_
Object for the DRV8305 CTRL05 register.
typedef struct _DRV_SPI_8305_Ctrl06_t_ DRV_SPI_8305_Ctrl06_t_
Object for the DRV8305 CTRL06 register.
typedef struct _DRV_SPI_8305_Ctrl07_t_ DRV_SPI_8305_Ctrl07_t_
Object for the DRV8305 CTRL07 register.
typedef struct _DRV_SPI_8305_Ctrl08_t_ DRV_SPI_8305_Ctrl08_t_
Object for the DRV8305 CTRL08 register.
typedef struct _DRV_SPI_8305_Ctrl09_t_ DRV_SPI_8305_Ctrl09_t_
Object for the DRV8305 CTRL09 register.
typedef struct _DRV_SPI_8305_Ctrl0A_t_ DRV_SPI_8305_Ctrl0A_t_
Object for the DRV8305 CTRL0A register.
typedef struct _DRV_SPI_8305_Ctrl0B_t_ DRV_SPI_8305_Ctrl0B_t_
Object for the DRV8305 CTRL0B register.
typedef struct _DRV_SPI_8305_Ctrl0C_t_ DRV_SPI_8305_Ctrl0C_t_
Object for the DRV8305 CTRL0C register.
typedef struct _DRV_SPI_8305_Stat01_t_ DRV_SPI_8305_Stat01_t_
Object for the DRV8305 STATUS01 register.
typedef struct _DRV_SPI_8305_Stat02_t_ DRV_SPI_8305_Stat02_t_
Object for the DRV8305 STATUS02 register.
typedef struct _DRV_SPI_8305_Stat03_t_ DRV_SPI_8305_Stat03_t_
Object for the DRV8305 STATUS03 register.
typedef struct _DRV_SPI_8305_Stat04_t_ DRV_SPI_8305_Stat04_t_
Object for the DRV8305 STATUS04 register.
typedef struct _DRV_SPI_8305_Vars_t_ DRV_SPI_8305_Vars_t
Object for the DRV8305 registers and commands.
Enumeration Type Documentation
enum DRV8305_Address_e
Enumeration for the register addresses.
Enumerator
Address_Status_1
Status Register 1.
Address_Status_2
Status Register 2.
Address_Status_3
Status Register 3.
Address_Status_4
Status Register 4.
Address_Control_5
Control Register 5.
Address_Control_6
Control Register 6.
Address_Control_7
Control Register 7.
Address_Control_8
Control Register 8.
Address_Control_9
Control Register 9.
Address_Control_A
Control Register A.
Address_Control_B
Control Register B.
Address_Control_C
Control Register C.
Definition at line 849 of file drv8305.h.
enum DRV8305_CTRL05_PeakSinkCurHS_e
Enumeration for the high side gate drive peak sink current.
Enumerator
ISink_HS_0p020_A
IDRIVEN_HS = 0.020A.
ISink_HS_0p030_A
IDRIVEN_HS = 0.030A.
ISink_HS_0p040_A
IDRIVEN_HS = 0.040A.
ISink_HS_0p050_A
IDRIVEN_HS = 0.050A.
ISink_HS_0p060_A
IDRIVEN_HS = 0.060A.
ISink_HS_0p070_A
IDRIVEN_HS = 0.070A.
ISink_HS_0p125_A
IDRIVEN_HS = 0.125A.
ISink_HS_0p250_A
IDRIVEN_HS = 0.250A.
ISink_HS_0p500_A
IDRIVEN_HS = 0.500A.
ISink_HS_0p750_A
IDRIVEN_HS = 0.750A.
ISink_HS_1p000_A
IDRIVEN_HS = 1.000A.
ISink_HS_1p250_A
IDRIVEN_HS = 1.250A.
Definition at line 567 of file drv8305.h.
enum DRV8305_CTRL05_PeakSourCurHS_e
Enumeration for the high side gate drive peak source current.
Enumerator
ISour_HS_0p010_A
IDRIVEP_HS = 0.010A.
ISour_HS_0p020_A
IDRIVEP_HS = 0.020A.
ISour_HS_0p030_A
IDRIVEP_HS = 0.030A.
ISour_HS_0p040_A
IDRIVEP_HS = 0.040A.
ISour_HS_0p050_A
IDRIVEP_HS = 0.050A.
ISour_HS_0p060_A
IDRIVEP_HS = 0.060A.
ISour_HS_0p070_A
IDRIVEP_HS = 0.070A.
ISour_HS_0p125_A
IDRIVEP_HS = 0.125A.
ISour_HS_0p250_A
IDRIVEP_HS = 0.250A.
ISour_HS_0p500_A
IDRIVEP_HS = 0.500A.
ISour_HS_0p750_A
IDRIVEP_HS = 0.750A.
ISour_HS_1p000_A
IDRIVEP_HS = 1.000A.
Definition at line 548 of file drv8305.h.
enum DRV8305_CTRL05_PeakSourTime_e
Enumeration for the high side and low side gate drive peak source time.
Enumerator
TSour_250_ns
TDRIVEN = 250ns.
TSour_500_ns
TDRIVEN = 500ns.
TSour_1000_ns
TDRIVEN = 1000ns.
TSour_2000_ns
TDRIVEN = 2000ns.
Definition at line 586 of file drv8305.h.
enum DRV8305_CTRL06_PeakSinkCurLS_e
Enumeration for the low side gate drive peak sink current.
Enumerator
ISink_LS_0p020_A
IDRIVEN_LS = 0.020A.
ISink_LS_0p030_A
IDRIVEN_LS = 0.030A.
ISink_LS_0p040_A
IDRIVEN_LS = 0.040A.
ISink_LS_0p050_A
IDRIVEN_LS = 0.050A.
ISink_LS_0p060_A
IDRIVEN_LS = 0.060A.
ISink_LS_0p070_A
IDRIVEN_LS = 0.070A.
ISink_LS_0p125_A
IDRIVEN_LS = 0.125A.
ISink_LS_0p250_A
IDRIVEN_LS = 0.250A.
ISink_LS_0p500_A
IDRIVEN_LS = 0.500A.
ISink_LS_0p750_A
IDRIVEN_LS = 0.750A.
ISink_LS_1p000_A
IDRIVEN_LS = 1.000A.
ISink_LS_1p250_A
IDRIVEN_LS = 1.250A.
Definition at line 616 of file drv8305.h.
enum DRV8305_CTRL06_PeakSinkTime_e
Enumeration for the high side and low side gate drive peak sink time.
Enumerator
TSink_250_ns
TDRIVEP = 250ns.
TSink_500_ns
TDRIVEP = 500ns.
TSink_1000_ns
TDRIVEP = 1000ns.
TSink_2000_ns
TDRIVEP = 2000ns.
Definition at line 635 of file drv8305.h.
enum DRV8305_CTRL06_PeakSourCurLS_e
Enumeration for the low side gate drive peak source current.
Enumerator
ISour_LS_0p010_A
IDRIVEP_LS = 0.010A.
ISour_LS_0p020_A
IDRIVEP_LS = 0.020A.
ISour_LS_0p030_A
IDRIVEP_LS = 0.030A.
ISour_LS_0p040_A
IDRIVEP_LS = 0.040A.
ISour_LS_0p050_A
IDRIVEP_LS = 0.050A.
ISour_LS_0p060_A
IDRIVEP_LS = 0.060A.
ISour_LS_0p070_A
IDRIVEP_LS = 0.070A.
ISour_LS_0p125_A
IDRIVEP_LS = 0.125A.
ISour_LS_0p250_A
IDRIVEP_LS = 0.250A.
ISour_LS_0p500_A
IDRIVEP_LS = 0.500A.
ISour_LS_0p750_A
IDRIVEP_LS = 0.750A.
ISour_LS_1p000_A
IDRIVEP_LS = 1.000A.
Definition at line 597 of file drv8305.h.
enum DRV8305_CTRL07_CommOption_e
Enumeration for the driver commutation mode in 1 input.
Enumerator
Diod
COMM_OPT = Diode free wheeling.
Actv
COMM_OPT = Active free wheeling.
Definition at line 693 of file drv8305.h.
enum DRV8305_CTRL07_DeadTime_e
Enumeration for the driver dead time.
Enumerator
DeadTime_40_ns
DEAD_TIME = 40ns.
DeadTime_60_ns
DEAD_TIME = 60ns.
DeadTime_100_ns
DEAD_TIME = 100ns.
DeadTime_500_ns
DEAD_TIME = 500ns.
DeadTime_1000_ns
DEAD_TIME = 1000ns.
DeadTime_2000_ns
DEAD_TIME = 2000ns.
DeadTime_4000_ns
DEAD_TIME = 4000ns.
DeadTime_6000_ns
DEAD_TIME = 6000ns.
Definition at line 668 of file drv8305.h.
enum DRV8305_CTRL07_PwmMode_e
Enumeration for the driver PWM mode.
Enumerator
PwmMode_6
PWM_MODE = 6 inputs.
PwmMode_3
PWM_MODE = 3 inputs.
PwmMode_1
PWM_MODE = 1 input.
Definition at line 683 of file drv8305.h.
enum DRV8305_CTRL07_VDSBlanking_e
Enumeration for the VDS sense blanking time.
Enumerator
VDSBlnk_0_us
TBLANK = 0us.
VDSBlnk_2_us
TBLANK = 2us.
VDSBlnk_4_us
TBLANK = 4us.
VDSBlnk_8_us
TBLANK = 8us.
Definition at line 657 of file drv8305.h.
enum DRV8305_CTRL07_VDSDeglitch_e
Enumeration for the VDS sense deglitch time.
Enumerator
VDSDeg_0_us
TVDS = 0us.
VDSDeg_2_us
TVDS = 2us.
VDSDeg_4_us
TVDS = 4us.
VDSDeg_8_us
TVDS = 8us.
Definition at line 646 of file drv8305.h.
enum DRV8305_CTRL09_WatchDelay_e
Enumeration for the IC's watchdog timer.
Enumerator
WD_Dly_10_ms
WD_DLY = 10ms.
WD_Dly_20_ms
WD_DLY = 20ms.
WD_Dly_50_ms
WD_DLY = 50ms.
WD_Dly_100_ms
WD_DLY = 100ms.
Definition at line 702 of file drv8305.h.
enum DRV8305_CTRL0A_CSBlank_e
Enumeration for the blanking time of the shunt amplifiers.
Enumerator
Blank_0p00_us
CS_BLANK = 0.0us.
Blank_0p50_us
CS_BLANK = 0.5us.
Blank_2p50_us
CS_BLANK = 2.5us.
Blank_10p0_us
CS_BLANK = 10.0us.
Definition at line 746 of file drv8305.h.
enum DRV8305_CTRL0A_CSGain1_e
Enumeration for the gain of shunt amplifier 1.
Enumerator
Gain1_10VpV
GAIN_CS1 = 10V/V.
Gain1_20VpV
GAIN_CS1 = 20V/V.
Gain1_40VpV
GAIN_CS1 = 40V/V.
Gain1_80VpV
GAIN_CS1 = 80V/V.
Definition at line 713 of file drv8305.h.
enum DRV8305_CTRL0A_CSGain2_e
Enumeration for the gain of shunt amplifier 2.
Enumerator
Gain2_10VpV
GAIN_CS2 = 10V/V.
Gain2_20VpV
GAIN_CS2 = 20V/V.
Gain2_40VpV
GAIN_CS2 = 40V/V.
Gain2_80VpV
GAIN_CS2 = 80V/V.
Definition at line 724 of file drv8305.h.
enum DRV8305_CTRL0A_CSGain3_e
Enumeration for the gain of shunt amplifier 3.
Enumerator
Gain3_10VpV
GAIN_CS3 = 10V/V.
Gain3_20VpV
GAIN_CS3 = 20V/V.
Gain3_40VpV
GAIN_CS3 = 40V/V.
Gain3_80VpV
GAIN_CS3 = 80V/V.
Definition at line 735 of file drv8305.h.
enum DRV8305_CTRL0A_DcCalMode_e
Enumeration for the DC calibration modes.
Enumerator
DcCalMode_Ch1_Load
Shunt amplifier 1 connected to load via input pins.
DcCalMode_Ch1_NoLoad
Shunt amplifier 1 disconnected from load and input pins are shorted.
DcCalMode_Ch2_Load
Shunt amplifier 2 connected to load via input pins.
DcCalMode_Ch2_NoLoad
Shunt amplifier 2 disconnected from load and input pins are shorted.
DcCalMode_Ch3_Load
Shunt amplifier 3 connected to load via input pins.
DcCalMode_Ch3_NoLoad
Shunt amplifier 3 disconnected from load and input pins are shorted.
Definition at line 757 of file drv8305.h.
enum DRV8305_CTRL0B_SleepDelay_e
Enumeration for the delay to power down VREG after SLEEP.
Enumerator
SleepDly_0_us
SLP_DLY = 0us.
SleepDly_10_us
SLP_DLY = 10us.
SleepDly_50_us
SLP_DLY = 50us.
SleepDly_1_ms
SLP_DLY = 1ms.
Definition at line 780 of file drv8305.h.
enum DRV8305_CTRL0B_VrefScaling_e
Enumeration for the VREF scaling factor.
Enumerator
Scaling_k_1
VREF_SCALING = 1.
Scaling_k_2
VREF_SCALING = 2.
Scaling_k_4
VREF_SCALING = 4.
Definition at line 791 of file drv8305.h.
enum DRV8305_CTRL0B_VregUvLevel_e
Enumeration for the VREG under voltage level.
Enumerator
UvLevel_10
VREG_UV_LEVEL = VSET-10%.
UvLevel_20
VREG_UV_LEVEL = VSET-20%.
UvLevel_30
VREG_UV_LEVEL = VSET-30%.
Definition at line 770 of file drv8305.h.
enum DRV8305_CTRL0C_VDSLevel_e
Enumeration for the VDS comparator threshold.
Enumerator
VDS_Level_0p060_V
VDS_LEVEL = 0.060V.
VDS_Level_0p068_V
VDS_LEVEL = 0.068V.
VDS_Level_0p076_V
VDS_LEVEL = 0.076V.
VDS_Level_0p086_V
VDS_LEVEL = 0.086V.
VDS_Level_0p097_V
VDS_LEVEL = 0.097V.
VDS_Level_0p109_V
VDS_LEVEL = 0.109V.
VDS_Level_0p123_V
VDS_LEVEL = 0.123V.
VDS_Level_0p138_V
VDS_LEVEL = 0.138V.
VDS_Level_0p155_V
VDS_LEVEL = 0.155V.
VDS_Level_0p175_V
VDS_LEVEL = 0.175V.
VDS_Level_0p197_V
VDS_LEVEL = 0.197V.
VDS_Level_0p222_V
VDS_LEVEL = 0.222V.
VDS_Level_0p250_V
VDS_LEVEL = 0.250V.
VDS_Level_0p282_V
VDS_LEVEL = 0.282V.
VDS_Level_0p317_V
VDS_LEVEL = 0.317V.
VDS_Level_0p358_V
VDS_LEVEL = 0.358V.
VDS_Level_0p403_V
VDS_LEVEL = 0.403V.
VDS_Level_0p454_V
VDS_LEVEL = 0.454V.
VDS_Level_0p511_V
VDS_LEVEL = 0.511V.
VDS_Level_0p576_V
VDS_LEVEL = 0.576V.
VDS_Level_0p648_V
VDS_LEVEL = 0.648V.
VDS_Level_0p730_V
VDS_LEVEL = 0.730V.
VDS_Level_0p822_V
VDS_LEVEL = 0.822V.
VDS_Level_0p926_V
VDS_LEVEL = 0.926V.
VDS_Level_1p043_V
VDS_LEVEL = 1.043V.
VDS_Level_1p175_V
VDS_LEVEL = 1.175V.
VDS_Level_1p324_V
VDS_LEVEL = 1.324V.
VDS_Level_1p491_V
VDS_LEVEL = 1.491V.
VDS_Level_1p679_V
VDS_LEVEL = 1.679V.
VDS_Level_1p892_V
VDS_LEVEL = 1.892V.
VDS_Level_2p131_V
VDS_LEVEL = 2.131V.
Definition at line 811 of file drv8305.h.
enum DRV8305_CTRL0C_VDSMode_e
Enumeration for the VDS report mode.
Enumerator
Latched_Shutdown
VDS_MODE = Latched shut down.
Report_Only
VDS_MODE = Report only.
Disable_VDS
VDS_MODE = Disabled.
Definition at line 801 of file drv8305.h.
enum DRV8305_CtrlMode_e
Enumeration for the R/W modes.
Enumerator
CtrlMode_Read
Read Mode.
CtrlMode_Write
Write Mode.
Definition at line 467 of file drv8305.h.
enum DRV8305_ShuntAmpNumber_e
Enumeration for the shunt amplifier number.
Enumerator
ShuntAmpNumber_1
Shunt amplifier number 1.
ShuntAmpNumber_2
Shunt amplifier number 2.
ShuntAmpNumber_3
Shunt amplifier number 3.
Definition at line 868 of file drv8305.h.
enum DRV8305_STATUS01_WarningWatchdog_e
Enumeration for the Status 1 register, warning and watchdog reset.
Enumerator
OTW
Over temperature warning.
TEMP_FLAG3
Junction temperature flag setting 3.
TEMP_FLAG2
Junction temperature flag setting 2.
TEMP_FLAG1
Junction temperature flag setting 1.
VCPH_UVFL
VCPH under voltage protection warning.
VDS_STATUS
Real time "OR" of 0x02[D5:10].
PVDD_OVFL
PVDD over voltage protection warning.
PVDD_UVFL
PVDD under voltage protection warning.
TEMP_FLAG4
Junction temperature flag setting 4 (no warning)
STAT01_RSV1
Reserved.
FAULT
FAULT type, 0-Warning, 1-Latched.
Definition at line 476 of file drv8305.h.
enum DRV8305_STATUS02_OvVdsFaults_e
Enumeration for the Status 2 register, OV/VDS faults.
Enumerator
SNS_A_OCP
Sense amp A over current.
SNS_B_OCP
Sense amp B over current.
SNS_C_OCP
Sense amp C over current.
STAT02_RSV2
Reserved.
STAT02_RSV1
Reserved.
FETLC_VDS
C low side, VDS fault.
FETHC_VDS
C high side, VDS fault.
FETLB_VDS
B low side, VDS fault.
FETHB_VDS
B high side, VDS fault.
FETLA_VDS
A low side, VDS fault.
FETHA_VDS
A high side, VDS fault.
Definition at line 494 of file drv8305.h.
enum DRV8305_STATUS03_ICFaults_e
Enumeration for the Status 3 register, IC faults.
Enumerator
VCPH_OVLO_ABS
VCPH over voltage protection fault (relative to GND)
VCPH_OVLO
VCPH over voltage protection warning.
VCPH_UVLO2
VCPH under voltage protection fault.
STAT03_RSV2
Reserved.
VCP_LSD_UVLO2
VCP_LSD under voltage protection fault.
AVDD_UVLO
AVDD under voltage protection fault.
VREG_UV
VREG under voltage protection fault.
STAT03_RSV1
Reserved.
OTS
Over temperature shut down fault.
WD_FAULT
Watchdog fault.
PVDD_UVLO2
PVDD under voltage protection fault.
Definition at line 512 of file drv8305.h.
enum DRV8305_STATUS04_VgsFaults_e
Enumeration for the Status 4 register, Vgs faults.
Enumerator
STAT04_RSV5
Reserved.
STAT04_RSV4
Reserved.
STAT04_RSV3
Reserved.
STAT04_RSV2
Reserved.
STAT04_RSV1
Reserved.
FETLC_VGS
C low side, VGS fault.
FETHC_VGS
C high side, VGS fault.
FETLB_VGS
B low side, VGS fault.
FETHB_VGS
B high side, VGS fault.
FETLA_VGS
A low side, VGS fault.
FETHA_VGS
A high side, VGS fault.
Definition at line 530 of file drv8305.h.
Function Documentation
static DRV8305_Word_t DRV8305_buildCtrlWord (const DRV8305_CtrlMode_e ctrlMode, const DRV8305_Address_e regAddr, const uint16_t data) inline static
Builds the control word.
Parameters
[in] ctrlMode The control mode
[in] regName The register name
[in] data The data
Returns
The control word
Definition at line 1120 of file drv8305.h.
References DRV8305_DATA_MASK.
Referenced by DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_enable (DRV8305_Handle handle)
Enables the DRV8305.
Parameters
[in] handle The DRV8305 handle
Definition at line 86 of file drv8305.c.
References Address_Status_1, DRV8305_readSpi(), DRV8305_STATUS01_FAULT_BITS, _DRV8305_Obj_::enableTimeOut, GPIO_setHigh(), _DRV8305_Obj_::gpioHandle, and _DRV8305_Obj_::gpioNumber.
DRV8305_CTRL07_CommOption_e DRV8305_getCommOption (DRV8305_Handle handle)
Gets the driver commutation mode for 1PWM mode.
Parameters
[in] handle The DRV8305 handle
Returns
The commutation mode
Definition at line 254 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_COMM_OPT_BITS, and DRV8305_readSpi().
DRV8305_CTRL0A_CSBlank_e DRV8305_getCSBlank (DRV8305_Handle handle)
Gets the blanking time of the shunt amplifiers.
Parameters
[in] handle The DRV8305 handle
Returns
The amplifier blanking time, us
Definition at line 324 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_CS_BLANK_BITS, and DRV8305_readSpi().
DRV8305_CTRL0A_CSGain1_e DRV8305_getCSGain1 (DRV8305_Handle handle)
Gets the gain of shunt amplifier 1.
Parameters
[in] handle The DRV8305 handle
Returns
The amplifier gain, V/V
Definition at line 282 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_GAIN_CS1_BITS, and DRV8305_readSpi().
DRV8305_CTRL0A_CSGain2_e DRV8305_getCSGain2 (DRV8305_Handle handle)
Gets the gain of shunt amplifier 2.
Parameters
[in] handle The DRV8305 handle
Returns
The amplifier gain, V/V
Definition at line 296 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_GAIN_CS2_BITS, and DRV8305_readSpi().
DRV8305_CTRL0A_CSGain3_e DRV8305_getCSGain3 (DRV8305_Handle handle)
Gets the gain of shunt amplifier 3.
Parameters
[in] handle The DRV8305 handle
Returns
The amplifier gain, V/V
Definition at line 310 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_GAIN_CS3_BITS, and DRV8305_readSpi().
DRV8305_CTRL0A_DcCalMode_e DRV8305_getDcCalMode (DRV8305_Handle handle, const DRV8305_ShuntAmpNumber_e ampNumber)
Gets the DC calibration mode.
Parameters
[in] handle The DRV8305 handle
[in] ampNumber The shunt amplifier number
Returns
The DC calibration mode
Definition at line 338 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_DC_CAL_CH1_BITS, DRV8305_CTRL0A_DC_CAL_CH2_BITS, DRV8305_CTRL0A_DC_CAL_CH3_BITS, DRV8305_readSpi(), ShuntAmpNumber_1, ShuntAmpNumber_2, and ShuntAmpNumber_3.
DRV8305_CTRL07_DeadTime_e DRV8305_getDeadTime (DRV8305_Handle handle)
Gets the driver dead time.
Parameters
[in] handle The DRV8305 handle
Returns
The dead time, ns
Definition at line 226 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_DEAD_TIME_BITS, and DRV8305_readSpi().
DRV8305_CTRL05_PeakSinkCurHS_e DRV8305_getPeakSinkCurHS (DRV8305_Handle handle)
Gets the high side gate drive peak sink current level.
Parameters
[in] handle The DRV8305 handle
Returns
The peak sink current level, A
Definition at line 128 of file drv8305.c.
References Address_Control_5, DRV8305_CTRL05_IDRIVEN_HS_BITS, and DRV8305_readSpi().
DRV8305_CTRL06_PeakSinkCurLS_e DRV8305_getPeakSinkCurLS (DRV8305_Handle handle)
Gets the low side side gate drive peak sink current level.
Parameters
[in] handle The DRV8305 handle
Returns
The peak sink current level, A
Definition at line 170 of file drv8305.c.
References Address_Control_6, DRV8305_CTRL06_IDRIVEN_LS_BITS, and DRV8305_readSpi().
DRV8305_CTRL06_PeakSinkTime_e DRV8305_getPeakSinkTime (DRV8305_Handle handle)
Gets the high side and low side gate drive peak sink time.
Parameters
[in] handle The DRV8305 handle
Returns
The peak sink time, ns
Definition at line 184 of file drv8305.c.
References Address_Control_6, DRV8305_CTRL06_TDRIVEP_BITS, and DRV8305_readSpi().
DRV8305_CTRL05_PeakSourCurHS_e DRV8305_getPeakSourCurHS (DRV8305_Handle handle)
Gets the high side gate drive peak source current level.
Parameters
[in] handle The DRV8305 handle
Returns
The peak source current level, A
Definition at line 114 of file drv8305.c.
References Address_Control_5, DRV8305_CTRL05_IDRIVEP_HS_BITS, and DRV8305_readSpi().
DRV8305_CTRL06_PeakSourCurLS_e DRV8305_getPeakSourCurLS (DRV8305_Handle handle)
Gets the low side gate drive peak source current level.
Parameters
[in] handle The DRV8305 handle
Returns
The peak source current level, A
Definition at line 156 of file drv8305.c.
References Address_Control_6, DRV8305_CTRL06_IDRIVEP_LS_BITS, and DRV8305_readSpi().
DRV8305_CTRL05_PeakSourTime_e DRV8305_getPeakSourTime (DRV8305_Handle handle)
Gets the high side and low side gate drive peak source time.
Parameters
[in] handle The DRV8305 handle
Returns
The peak source time, ns
Definition at line 142 of file drv8305.c.
References Address_Control_5, DRV8305_CTRL05_TDRIVEN_BITS, and DRV8305_readSpi().
DRV8305_CTRL07_PwmMode_e DRV8305_getPwmMode (DRV8305_Handle handle)
Gets the driver PWM mode.
Parameters
[in] handle The DRV8305 handle
Returns
The PWM mode
Definition at line 240 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_PWM_MODE_BITS, and DRV8305_readSpi().
DRV8305_CTRL0B_SleepDelay_e DRV8305_getSleepDelay (DRV8305_Handle handle)
Gets the delay time to power down VREF after SLEEP.
Parameters
[in] handle The DRV8305 handle
Returns
The delay time, us
Definition at line 377 of file drv8305.c.
References Address_Control_B, DRV8305_CTRL0B_SLP_DLY_BITS, and DRV8305_readSpi().
DRV8305_CTRL07_VDSBlanking_e DRV8305_getVDSBlanking (DRV8305_Handle handle)
Gets the VDS sense blanking time.
Parameters
[in] handle The DRV8305 handle
Returns
The blanking time time, us
Definition at line 212 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_TBLANK_BITS, and DRV8305_readSpi().
DRV8305_CTRL07_VDSDeglitch_e DRV8305_getVDSDeglitch (DRV8305_Handle handle)
Gets the VDS sense deglitch time.
Parameters
[in] handle The DRV8305 handle
Returns
The deglitch time time, us
Definition at line 198 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_TVDS_BITS, and DRV8305_readSpi().
DRV8305_CTRL0C_VDSLevel_e DRV8305_getVDSLevel (DRV8305_Handle handle)
Gets the VDS OC level.
Parameters
[in] handle The DRV8305 handle
Returns
The VDS OC level, V
Definition at line 419 of file drv8305.c.
References Address_Control_C, DRV8305_CTRL0C_VDS_LEVEL_BITS, and DRV8305_readSpi().
DRV8305_CTRL0C_VDSMode_e DRV8305_getVDSMode (DRV8305_Handle handle)
Gets the VDS protection mode.
Parameters
[in] handle The DRV8305 handle
Returns
The VDS protection mode
Definition at line 405 of file drv8305.c.
References Address_Control_C, DRV8305_CTRL0C_VDS_MODE_BITS, and DRV8305_readSpi().
DRV8305_CTRL0B_VrefScaling_e DRV8305_getVrefScaling (DRV8305_Handle handle)
Gets the VREF scaling factor.
Parameters
[in] handle The DRV8305 handle
Returns
The VREF scaling factor
Definition at line 391 of file drv8305.c.
References Address_Control_B, DRV8305_CTRL0B_VREF_SCALING_BITS, and DRV8305_readSpi().
DRV8305_CTRL0B_VregUvLevel_e DRV8305_getVregUvLevel (DRV8305_Handle handle)
Gets the under voltage level of VREF.
Parameters
[in] handle The DRV8305 handle
Returns
The UV level, %
Definition at line 363 of file drv8305.c.
References Address_Control_B, DRV8305_CTRL0B_VREG_UV_LEVEL_BITS, and DRV8305_readSpi().
DRV8305_CTRL09_WatchDelay_e DRV8305_getWatchDelay (DRV8305_Handle handle)
Gets the watchdog timer setting.
Parameters
[in] handle The DRV8305 handle
Returns
The watchdog timer setting, ms
Definition at line 268 of file drv8305.c.
References Address_Control_9, DRV8305_CTRL09_WD_DLY_BITS, and DRV8305_readSpi().
DRV8305_Handle DRV8305_init (void * pMemory, const size_t numBytes)
Initializes the DRV8305 object.
Parameters
[in] pMemory A pointer to the memory for the DRV8305 object
[in] numBytes The number of bytes allocated for the DRV8305 object, bytes
Returns
The DRV8305 object handle
Definition at line 69 of file drv8305.c.
References DRV8305_resetEnableTimeout(), and DRV8305_resetRxTimeout().
bool DRV8305_isFault (DRV8305_Handle handle)
Determines if DRV8305 fault has occurred.
Parameters
[in] handle The DRV8305 handle
Returns
A boolean value denoting if a fault has occurred (true) or not (false)
Definition at line 897 of file drv8305.c.
References Address_Status_1, DRV8305_readSpi(), and DRV8305_STATUS01_FAULT_BITS.
void DRV8305_readData (DRV8305_Handle handle, DRV_SPI_8305_Vars_t * Spi_8305_Vars)
Read from the DRV8305 SPI registers.
Parameters
[in] handle The DRV8305 handle
[in] Spi_8305_Vars The (DRV_SPI_8305_Vars_t) structure that contains all DRV8305 Status/Control register options
Definition at line 1255 of file drv8305.c.
References Address_Control_5, Address_Control_6, Address_Control_7, Address_Control_9, Address_Control_A, Address_Control_B, Address_Control_C, Address_Status_1, Address_Status_2, Address_Status_3, Address_Status_4, _DRV_SPI_8305_Stat03_t_::AVDD_UVLO, _DRV_SPI_8305_Ctrl09_t_::CLR_FLTS, _DRV_SPI_8305_Ctrl07_t_::COMM_OPT, _DRV_SPI_8305_Ctrl0A_t_::CS_BLANK, _DRV_SPI_8305_Ctrl05_t_::CTRL05_RSV1, _DRV_SPI_8305_Ctrl06_t_::CTRL06_RSV1, _DRV_SPI_8305_Ctrl07_t_::CTRL07_RSV1, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV1, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV2, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV3, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV4, _DRV_SPI_8305_Ctrl0C_t_::CTRL0C_RSV1, _DRV_SPI_8305_Ctrl0C_t_::CTRL0C_RSV2, _DRV_SPI_8305_Ctrl0C_t_::CTRL0C_RSV3, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_05, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_06, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_07, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_09, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_0A, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_0B, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_0C, _DRV_SPI_8305_Ctrl0A_t_::DC_CAL_CH1, _DRV_SPI_8305_Ctrl0A_t_::DC_CAL_CH2, _DRV_SPI_8305_Ctrl0A_t_::DC_CAL_CH3, _DRV_SPI_8305_Ctrl07_t_::DEAD_TIME, _DRV_SPI_8305_Ctrl09_t_::DIS_GDRV_FAULT, _DRV_SPI_8305_Ctrl0B_t_::DIS_PWRGD, _DRV_SPI_8305_Ctrl09_t_::DIS_SNS_OCP, _DRV_SPI_8305_Ctrl09_t_::DISABLE, DRV8305_CTRL05_IDRIVEN_HS_BITS, DRV8305_CTRL05_IDRIVEP_HS_BITS, DRV8305_CTRL05_RESERVED1_BITS, DRV8305_CTRL05_TDRIVEN_BITS, DRV8305_CTRL06_IDRIVEN_LS_BITS, DRV8305_CTRL06_IDRIVEP_LS_BITS, DRV8305_CTRL06_TDRIVEP_BITS, DRV8305_CTRL07_COMM_OPT_BITS, DRV8305_CTRL07_DEAD_TIME_BITS, DRV8305_CTRL07_PWM_MODE_BITS, DRV8305_CTRL07_RESERVED1_BITS, DRV8305_CTRL07_TBLANK_BITS, DRV8305_CTRL07_TVDS_BITS, DRV8305_CTRL09_CLR_FLTS_BITS, DRV8305_CTRL09_DIS_GDRV_FAULT_BITS, DRV8305_CTRL09_DIS_SNS_OCP_BITS, DRV8305_CTRL09_DISABLE_BITS, DRV8305_CTRL09_EN_SNS_CLAMP_BITS, DRV8305_CTRL09_FLIP_OTS_BITS, DRV8305_CTRL09_SET_VCPH_UV_BITS, DRV8305_CTRL09_SLEEP_BITS, DRV8305_CTRL09_WD_DLY_BITS, DRV8305_CTRL09_WD_EN_BITS, DRV8305_CTRL0A_CS_BLANK_BITS, DRV8305_CTRL0A_DC_CAL_CH1_BITS, DRV8305_CTRL0A_DC_CAL_CH2_BITS, DRV8305_CTRL0A_DC_CAL_CH3_BITS, DRV8305_CTRL0A_GAIN_CS1_BITS, DRV8305_CTRL0A_GAIN_CS2_BITS, DRV8305_CTRL0A_GAIN_CS3_BITS, DRV8305_CTRL0B_DIS_PWRGD_BITS, DRV8305_CTRL0B_RESERVED1_BITS, DRV8305_CTRL0B_RESERVED2_BITS, DRV8305_CTRL0B_RESERVED3_BITS, DRV8305_CTRL0B_RESERVED4_BITS, DRV8305_CTRL0B_SLP_DLY_BITS, DRV8305_CTRL0B_VREF_SCALING_BITS, DRV8305_CTRL0B_VREG_UV_LEVEL_BITS, DRV8305_CTRL0C_RESERVED1_BITS, DRV8305_CTRL0C_RESERVED2_BITS, DRV8305_CTRL0C_RESERVED3_BITS, DRV8305_CTRL0C_VDS_LEVEL_BITS, DRV8305_CTRL0C_VDS_MODE_BITS, DRV8305_readSpi(), DRV8305_STATUS01_FAULT_BITS, DRV8305_STATUS01_OTW_BITS, DRV8305_STATUS01_PVDD_OVFL_BITS, DRV8305_STATUS01_PVDD_UVFL_BITS, DRV8305_STATUS01_RESERVED1_BITS, DRV8305_STATUS01_TEMP_FLAG1_BITS, DRV8305_STATUS01_TEMP_FLAG2_BITS, DRV8305_STATUS01_TEMP_FLAG3_BITS, DRV8305_STATUS01_TEMP_FLAG4_BITS, DRV8305_STATUS01_VCPH_UVFL_BITS, DRV8305_STATUS01_VDS_STATUS_BITS, DRV8305_STATUS02_FETHA_VDS_BITS, DRV8305_STATUS02_FETHB_VDS_BITS, DRV8305_STATUS02_FETHC_VDS_BITS, DRV8305_STATUS02_FETLA_VDS_BITS, DRV8305_STATUS02_FETLB_VDS_BITS, DRV8305_STATUS02_FETLC_VDS_BITS, DRV8305_STATUS02_RESERVED1_BITS, DRV8305_STATUS02_RESERVED2_BITS, DRV8305_STATUS02_SNS_A_OCP_BITS, DRV8305_STATUS02_SNS_B_OCP_BITS, DRV8305_STATUS02_SNS_C_OCP_BITS, DRV8305_STATUS03_AVDD_UVLO_BITS, DRV8305_STATUS03_OTS_BITS, DRV8305_STATUS03_PVDD_UVLO2_BITS, DRV8305_STATUS03_RESERVED1_BITS, DRV8305_STATUS03_RESERVED2_BITS, DRV8305_STATUS03_VCP_LSD_UVLO2_BITS, DRV8305_STATUS03_VCPH_OVLO_ABS_BITS, DRV8305_STATUS03_VCPH_OVLO_BITS, DRV8305_STATUS03_VCPH_UVLO2_BITS, DRV8305_STATUS03_VREG_UV_BITS, DRV8305_STATUS03_WD_FAULT_BITS, DRV8305_STATUS04_FETHA_VGS_BITS, DRV8305_STATUS04_FETHB_VGS_BITS, DRV8305_STATUS04_FETHC_VGS_BITS, DRV8305_STATUS04_FETLA_VGS_BITS, DRV8305_STATUS04_FETLB_VGS_BITS, DRV8305_STATUS04_FETLC_VGS_BITS, DRV8305_STATUS04_RESERVED1_BITS, DRV8305_STATUS04_RESERVED2_BITS, DRV8305_STATUS04_RESERVED3_BITS, DRV8305_STATUS04_RESERVED4_BITS, DRV8305_STATUS04_RESERVED5_BITS, _DRV_SPI_8305_Ctrl09_t_::EN_SNS_CLAMP, _DRV_SPI_8305_Stat01_t_::FAULT, _DRV_SPI_8305_Stat02_t_::FETHA_VDS, _DRV_SPI_8305_Stat04_t_::FETHA_VGS, _DRV_SPI_8305_Stat02_t_::FETHB_VDS, _DRV_SPI_8305_Stat04_t_::FETHB_VGS, _DRV_SPI_8305_Stat02_t_::FETHC_VDS, _DRV_SPI_8305_Stat04_t_::FETHC_VGS, _DRV_SPI_8305_Stat02_t_::FETLA_VDS, _DRV_SPI_8305_Stat04_t_::FETLA_VGS, _DRV_SPI_8305_Stat02_t_::FETLB_VDS, _DRV_SPI_8305_Stat04_t_::FETLB_VGS, _DRV_SPI_8305_Stat02_t_::FETLC_VDS, _DRV_SPI_8305_Stat04_t_::FETLC_VGS, _DRV_SPI_8305_Ctrl09_t_::FLIP_OTS, _DRV_SPI_8305_Ctrl0A_t_::GAIN_CS1, _DRV_SPI_8305_Ctrl0A_t_::GAIN_CS2, _DRV_SPI_8305_Ctrl0A_t_::GAIN_CS3, _DRV_SPI_8305_Ctrl05_t_::IDRIVEN_HS, _DRV_SPI_8305_Ctrl06_t_::IDRIVEN_LS, _DRV_SPI_8305_Ctrl05_t_::IDRIVEP_HS, _DRV_SPI_8305_Ctrl06_t_::IDRIVEP_LS, _DRV_SPI_8305_Vars_t_::ManReadAddr, _DRV_SPI_8305_Vars_t_::ManReadCmd, _DRV_SPI_8305_Vars_t_::ManReadData, _DRV_SPI_8305_Stat03_t_::OTS, _DRV_SPI_8305_Stat01_t_::OTW, _DRV_SPI_8305_Stat01_t_::PVDD_OVFL, _DRV_SPI_8305_Stat01_t_::PVDD_UVFL, _DRV_SPI_8305_Stat03_t_::PVDD_UVLO2, _DRV_SPI_8305_Ctrl07_t_::PWM_MODE, _DRV_SPI_8305_Vars_t_::ReadCmd, _DRV_SPI_8305_Ctrl09_t_::SET_VCPH_UV, _DRV_SPI_8305_Ctrl09_t_::SLEEP, _DRV_SPI_8305_Ctrl0B_t_::SLP_DLY, _DRV_SPI_8305_Stat02_t_::SNS_A_OCP, _DRV_SPI_8305_Stat02_t_::SNS_B_OCP, _DRV_SPI_8305_Stat02_t_::SNS_C_OCP, _DRV_SPI_8305_Stat01_t_::STAT01_RSV1, _DRV_SPI_8305_Stat02_t_::STAT02_RSV1, _DRV_SPI_8305_Stat02_t_::STAT02_RSV2, _DRV_SPI_8305_Stat03_t_::STAT03_RSV1, _DRV_SPI_8305_Stat03_t_::STAT03_RSV2, _DRV_SPI_8305_Stat04_t_::STAT04_RSV1, _DRV_SPI_8305_Stat04_t_::STAT04_RSV2, _DRV_SPI_8305_Stat04_t_::STAT04_RSV3, _DRV_SPI_8305_Stat04_t_::STAT04_RSV4, _DRV_SPI_8305_Stat04_t_::STAT04_RSV5, _DRV_SPI_8305_Vars_t_::Stat_Reg_01, _DRV_SPI_8305_Vars_t_::Stat_Reg_02, _DRV_SPI_8305_Vars_t_::Stat_Reg_03, _DRV_SPI_8305_Vars_t_::Stat_Reg_04, _DRV_SPI_8305_Ctrl07_t_::TBLANK, _DRV_SPI_8305_Ctrl05_t_::TDRIVEN, _DRV_SPI_8305_Ctrl06_t_::TDRIVEP, _DRV_SPI_8305_Stat01_t_::TEMP_FLAG1, _DRV_SPI_8305_Stat01_t_::TEMP_FLAG2, _DRV_SPI_8305_Stat01_t_::TEMP_FLAG3, _DRV_SPI_8305_Stat01_t_::TEMP_FLAG4, _DRV_SPI_8305_Ctrl07_t_::TVDS, _DRV_SPI_8305_Stat03_t_::VCP_LSD_UVLO2, _DRV_SPI_8305_Stat03_t_::VCPH_OVLO, _DRV_SPI_8305_Stat03_t_::VCPH_OVLO_ABS, _DRV_SPI_8305_Stat01_t_::VCPH_UVFL, _DRV_SPI_8305_Stat03_t_::VCPH_UVLO2, _DRV_SPI_8305_Ctrl0C_t_::VDS_LEVEL, _DRV_SPI_8305_Ctrl0C_t_::VDS_MODE, _DRV_SPI_8305_Stat01_t_::VDS_STATUS, _DRV_SPI_8305_Ctrl0B_t_::VREF_SCALING, _DRV_SPI_8305_Stat03_t_::VREG_UV, _DRV_SPI_8305_Ctrl0B_t_::VREG_UV_LEVEL, _DRV_SPI_8305_Ctrl09_t_::WD_DLY, _DRV_SPI_8305_Ctrl09_t_::WD_EN, and _DRV_SPI_8305_Stat03_t_::WD_FAULT.
uint16_t DRV8305_readSpi (DRV8305_Handle handle, const DRV8305_Address_e regAddr)
Reads data from the DRV8305 register.
Parameters
[in] handle The DRV8305 handle
[in] regAddr The register address
Returns
The data value
Definition at line 1093 of file drv8305.c.
References CtrlMode_Read, DRV8305_buildCtrlWord(), DRV8305_DATA_MASK, _DRV8305_Obj_::RxTimeOut, SPI_enableRxFifo(), SPI_FifoStatus_1_Word, SPI_FifoStatus_Empty, SPI_getRxFifoStatus(), SPI_readEmu(), SPI_resetRxFifo(), SPI_write(), and _DRV8305_Obj_::spiHandle.
Referenced by DRV8305_enable(), DRV8305_getCommOption(), DRV8305_getCSBlank(), DRV8305_getCSGain1(), DRV8305_getCSGain2(), DRV8305_getCSGain3(), DRV8305_getDcCalMode(), DRV8305_getDeadTime(), DRV8305_getPeakSinkCurHS(), DRV8305_getPeakSinkCurLS(), DRV8305_getPeakSinkTime(), DRV8305_getPeakSourCurHS(), DRV8305_getPeakSourCurLS(), DRV8305_getPeakSourTime(), DRV8305_getPwmMode(), DRV8305_getSleepDelay(), DRV8305_getVDSBlanking(), DRV8305_getVDSDeglitch(), DRV8305_getVDSLevel(), DRV8305_getVDSMode(), DRV8305_getVrefScaling(), DRV8305_getVregUvLevel(), DRV8305_getWatchDelay(), DRV8305_isFault(), DRV8305_readData(), DRV8305_reset(), DRV8305_setCommOption(), DRV8305_setCSBlank(), DRV8305_setCSGain1(), DRV8305_setCSGain2(), DRV8305_setCSGain3(), DRV8305_setDcCalMode(), DRV8305_setDeadTime(), DRV8305_setPeakSinkCurHS(), DRV8305_setPeakSinkCurLS(), DRV8305_setPeakSinkTime(), DRV8305_setPeakSourCurHS(), DRV8305_setPeakSourTime(), DRV8305_setPwmMode(), DRV8305_setSleepDelay(), DRV8305_setupSpi(), DRV8305_setVDSBlanking(), DRV8305_setVDSDeglitch(), DRV8305_setVDSLevel(), DRV8305_setVDSMode(), DRV8305_setVrefScaling(), DRV8305_setVregUvLevel(), and DRV8305_setWatchDelay().
void DRV8305_reset (DRV8305_Handle handle)
Resets the DRV8305.
Parameters
[in] handle The DRV8305 handle
Definition at line 915 of file drv8305.c.
References Address_Control_9, DRV8305_CTRL09_CLR_FLTS_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
static void DRV8305_resetEnableTimeout (DRV8305_Handle handle) inline static
Resets the enable timeout flag.
Parameters
[in] handle The DRV8305 handle
Definition at line 1434 of file drv8305.h.
References _DRV8305_Obj_::enableTimeOut.
Referenced by DRV8305_init().
static void DRV8305_resetRxTimeout (DRV8305_Handle handle) inline static
Resets the RX fifo timeout flag.
Parameters
[in] handle The DRV8305 handle
Definition at line 1446 of file drv8305.h.
References _DRV8305_Obj_::RxTimeOut.
Referenced by DRV8305_init().
void DRV8305_setCommOption (DRV8305_Handle handle, const DRV8305_CTRL07_CommOption_e mode)
Sets the driver commutation mode for 1PWM mode.
Parameters
[in] handle The DRV8305 handle
[in] mode The commutation mode
Definition at line 646 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_COMM_OPT_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setCSBlank (DRV8305_Handle handle, const DRV8305_CTRL0A_CSBlank_e time)
Sets the blanking time of the shunt amplifiers.
Parameters
[in] handle The DRV8305 handle
[in] time The amplifier blanking time, us
Definition at line 746 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_CS_BLANK_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setCSGain1 (DRV8305_Handle handle, const DRV8305_CTRL0A_CSGain1_e gain)
Sets the gain of shunt amplifier 1.
Parameters
[in] handle The DRV8305 handle
[in] gain The amplifier gain, V/V
Definition at line 686 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_GAIN_CS1_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setCSGain2 (DRV8305_Handle handle, const DRV8305_CTRL0A_CSGain2_e gain)
Sets the gain of shunt amplifier 2.
Parameters
[in] handle The DRV8305 handle
[in] gain The amplifier gain, V/V
Definition at line 706 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_GAIN_CS2_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setCSGain3 (DRV8305_Handle handle, const DRV8305_CTRL0A_CSGain3_e gain)
Sets the gain of shunt amplifier 3.
Parameters
[in] handle The DRV8305 handle
[in] gain The amplifier gain, V/V
Definition at line 726 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_GAIN_CS3_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setDcCalMode (DRV8305_Handle handle, const DRV8305_ShuntAmpNumber_e ampNumber, const DRV8305_CTRL0A_DcCalMode_e mode)
Sets the DC calibration mode.
Parameters
[in] handle The DRV8305 handle
[in] ampNumber The shunt amplifier number
[in] mode The DC calibration mode
Definition at line 766 of file drv8305.c.
References Address_Control_A, DRV8305_CTRL0A_DC_CAL_CH1_BITS, DRV8305_CTRL0A_DC_CAL_CH2_BITS, DRV8305_CTRL0A_DC_CAL_CH3_BITS, DRV8305_readSpi(), DRV8305_writeSpi(), ShuntAmpNumber_1, ShuntAmpNumber_2, and ShuntAmpNumber_3.
void DRV8305_setDeadTime (DRV8305_Handle handle, const DRV8305_CTRL07_DeadTime_e time)
Sets the driver dead time.
Parameters
[in] handle The DRV8305 handle
[in] time The dead time, ns
Definition at line 606 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_DEAD_TIME_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setGpioHandle (DRV8305_Handle handle, GPIO_Handle gpioHandle)
Sets the GPIO handle in the DRV8305.
Parameters
[in] handle The DRV8305 handle
[in] gpioHandle The GPIO handle to use
Definition at line 444 of file drv8305.c.
References _DRV8301_Obj_::gpioHandle, and _DRV8305_Obj_::gpioHandle.
void DRV8305_setGpioNumber (DRV8305_Handle handle, GPIO_Number_e gpioNumber)
Sets the GPIO number in the DRV8305.
Parameters
[in] handle The DRV8305 handle
[in] gpioHandle The GPIO number to use
Definition at line 455 of file drv8305.c.
References _DRV8301_Obj_::gpioNumber, and _DRV8305_Obj_::gpioNumber.
void DRV8305_setPeakSinkCurHS (DRV8305_Handle handle, const DRV8305_CTRL05_PeakSinkCurHS_e level)
Sets the high side gate drive peak sink current level.
Parameters
[in] handle The DRV8305 handle
[in] level The peak sink current level, A
Definition at line 486 of file drv8305.c.
References Address_Control_5, DRV8305_CTRL05_IDRIVEN_HS_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setPeakSinkCurLS (DRV8305_Handle handle, const DRV8305_CTRL06_PeakSinkCurLS_e level)
Sets the low side side gate drive peak sink current level.
Parameters
[in] handle The DRV8305 handle
[in] level The peak sink current level, A
Definition at line 526 of file drv8305.c.
References Address_Control_6, DRV8305_CTRL06_IDRIVEP_LS_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setPeakSinkTime (DRV8305_Handle handle, const DRV8305_CTRL06_PeakSinkTime_e time)
Sets the high side and low side gate drive peak sink time.
Parameters
[in] handle The DRV8305 handle
[in] time The peak sink time, ns
Definition at line 546 of file drv8305.c.
References Address_Control_6, DRV8305_CTRL06_TDRIVEP_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setPeakSourCurHS (DRV8305_Handle handle, const DRV8305_CTRL05_PeakSourCurHS_e level)
Sets the high side gate drive peak source current level.
Parameters
[in] handle The DRV8305 handle
[in] level The peak source current level, A
Definition at line 466 of file drv8305.c.
References Address_Control_5, DRV8305_CTRL05_IDRIVEP_HS_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setPeakSourCurLS (DRV8305_Handle handle, const DRV8305_CTRL06_PeakSourCurLS_e level)
Sets the the low side gate drive peak source current level.
Parameters
[in] handle The DRV8305 handle
[in] level The peak source current level, A
void DRV8305_setPeakSourTime (DRV8305_Handle handle, const DRV8305_CTRL05_PeakSourTime_e time)
Sets the high side and low side gate drive peak source time.
Parameters
[in] handle The DRV8305 handle
[in] time The peak source time, ns
Definition at line 506 of file drv8305.c.
References Address_Control_5, DRV8305_CTRL05_TDRIVEN_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setPwmMode (DRV8305_Handle handle, const DRV8305_CTRL07_PwmMode_e mode)
Sets the driver PWM mode.
Parameters
[in] handle The DRV8305 handle
[in] mode The PWM mode
Definition at line 626 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_PWM_MODE_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setSleepDelay (DRV8305_Handle handle, const DRV8305_CTRL0B_SleepDelay_e time)
Sets the delay time to power down VREF after SLEEP.
Parameters
[in] handle The DRV8305 handle
[in] time The delay time, us
Definition at line 817 of file drv8305.c.
References Address_Control_B, DRV8305_CTRL0B_SLP_DLY_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setSpiHandle (DRV8305_Handle handle, SPI_Handle spiHandle)
Sets the SPI handle in the DRV8305.
Parameters
[in] handle The DRV8305 handle
[in] spiHandle The SPI handle to use
Definition at line 433 of file drv8305.c.
References _DRV8301_Obj_::spiHandle, and _DRV8305_Obj_::spiHandle.
void DRV8305_setupSpi (DRV8305_Handle handle, DRV_SPI_8305_Vars_t * Spi_8305_Vars)
Initialize the interface to all 8305 SPI variables.
Parameters
[in] handle The DRV8305 handle
Definition at line 933 of file drv8305.c.
References Address_Control_5, Address_Control_6, Address_Control_7, Address_Control_9, Address_Control_A, Address_Control_B, Address_Control_C, Address_Status_1, Address_Status_2, Address_Status_3, Address_Status_4, _DRV_SPI_8305_Stat03_t_::AVDD_UVLO, _DRV_SPI_8305_Ctrl09_t_::CLR_FLTS, _DRV_SPI_8305_Ctrl07_t_::COMM_OPT, _DRV_SPI_8305_Ctrl0A_t_::CS_BLANK, _DRV_SPI_8305_Ctrl05_t_::CTRL05_RSV1, _DRV_SPI_8305_Ctrl06_t_::CTRL06_RSV1, _DRV_SPI_8305_Ctrl07_t_::CTRL07_RSV1, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV1, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV2, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV3, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV4, _DRV_SPI_8305_Ctrl0C_t_::CTRL0C_RSV1, _DRV_SPI_8305_Ctrl0C_t_::CTRL0C_RSV2, _DRV_SPI_8305_Ctrl0C_t_::CTRL0C_RSV3, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_05, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_06, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_07, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_09, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_0A, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_0B, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_0C, _DRV_SPI_8305_Ctrl0A_t_::DC_CAL_CH1, _DRV_SPI_8305_Ctrl0A_t_::DC_CAL_CH2, _DRV_SPI_8305_Ctrl0A_t_::DC_CAL_CH3, _DRV_SPI_8305_Ctrl07_t_::DEAD_TIME, _DRV_SPI_8305_Ctrl09_t_::DIS_GDRV_FAULT, _DRV_SPI_8305_Ctrl0B_t_::DIS_PWRGD, _DRV_SPI_8305_Ctrl09_t_::DIS_SNS_OCP, _DRV_SPI_8305_Ctrl09_t_::DISABLE, DRV8305_CTRL05_IDRIVEN_HS_BITS, DRV8305_CTRL05_IDRIVEP_HS_BITS, DRV8305_CTRL05_RESERVED1_BITS, DRV8305_CTRL05_TDRIVEN_BITS, DRV8305_CTRL06_IDRIVEN_LS_BITS, DRV8305_CTRL06_IDRIVEP_LS_BITS, DRV8305_CTRL06_TDRIVEP_BITS, DRV8305_CTRL07_COMM_OPT_BITS, DRV8305_CTRL07_DEAD_TIME_BITS, DRV8305_CTRL07_PWM_MODE_BITS, DRV8305_CTRL07_RESERVED1_BITS, DRV8305_CTRL07_TBLANK_BITS, DRV8305_CTRL07_TVDS_BITS, DRV8305_CTRL09_CLR_FLTS_BITS, DRV8305_CTRL09_DIS_GDRV_FAULT_BITS, DRV8305_CTRL09_DIS_SNS_OCP_BITS, DRV8305_CTRL09_DISABLE_BITS, DRV8305_CTRL09_EN_SNS_CLAMP_BITS, DRV8305_CTRL09_FLIP_OTS_BITS, DRV8305_CTRL09_SET_VCPH_UV_BITS, DRV8305_CTRL09_SLEEP_BITS, DRV8305_CTRL09_WD_DLY_BITS, DRV8305_CTRL09_WD_EN_BITS, DRV8305_CTRL0A_CS_BLANK_BITS, DRV8305_CTRL0A_DC_CAL_CH1_BITS, DRV8305_CTRL0A_DC_CAL_CH2_BITS, DRV8305_CTRL0A_DC_CAL_CH3_BITS, DRV8305_CTRL0A_GAIN_CS1_BITS, DRV8305_CTRL0A_GAIN_CS2_BITS, DRV8305_CTRL0A_GAIN_CS3_BITS, DRV8305_CTRL0B_DIS_PWRGD_BITS, DRV8305_CTRL0B_RESERVED1_BITS, DRV8305_CTRL0B_RESERVED2_BITS, DRV8305_CTRL0B_RESERVED3_BITS, DRV8305_CTRL0B_RESERVED4_BITS, DRV8305_CTRL0B_SLP_DLY_BITS, DRV8305_CTRL0B_VREF_SCALING_BITS, DRV8305_CTRL0B_VREG_UV_LEVEL_BITS, DRV8305_CTRL0C_RESERVED1_BITS, DRV8305_CTRL0C_RESERVED2_BITS, DRV8305_CTRL0C_RESERVED3_BITS, DRV8305_CTRL0C_VDS_LEVEL_BITS, DRV8305_CTRL0C_VDS_MODE_BITS, DRV8305_readSpi(), DRV8305_STATUS01_FAULT_BITS, DRV8305_STATUS01_OTW_BITS, DRV8305_STATUS01_PVDD_OVFL_BITS, DRV8305_STATUS01_PVDD_UVFL_BITS, DRV8305_STATUS01_RESERVED1_BITS, DRV8305_STATUS01_TEMP_FLAG1_BITS, DRV8305_STATUS01_TEMP_FLAG2_BITS, DRV8305_STATUS01_TEMP_FLAG3_BITS, DRV8305_STATUS01_TEMP_FLAG4_BITS, DRV8305_STATUS01_VCPH_UVFL_BITS, DRV8305_STATUS01_VDS_STATUS_BITS, DRV8305_STATUS02_FETHA_VDS_BITS, DRV8305_STATUS02_FETHB_VDS_BITS, DRV8305_STATUS02_FETHC_VDS_BITS, DRV8305_STATUS02_FETLA_VDS_BITS, DRV8305_STATUS02_FETLB_VDS_BITS, DRV8305_STATUS02_FETLC_VDS_BITS, DRV8305_STATUS02_RESERVED1_BITS, DRV8305_STATUS02_RESERVED2_BITS, DRV8305_STATUS02_SNS_A_OCP_BITS, DRV8305_STATUS02_SNS_B_OCP_BITS, DRV8305_STATUS02_SNS_C_OCP_BITS, DRV8305_STATUS03_AVDD_UVLO_BITS, DRV8305_STATUS03_OTS_BITS, DRV8305_STATUS03_PVDD_UVLO2_BITS, DRV8305_STATUS03_RESERVED1_BITS, DRV8305_STATUS03_RESERVED2_BITS, DRV8305_STATUS03_VCP_LSD_UVLO2_BITS, DRV8305_STATUS03_VCPH_OVLO_ABS_BITS, DRV8305_STATUS03_VCPH_OVLO_BITS, DRV8305_STATUS03_VCPH_UVLO2_BITS, DRV8305_STATUS03_VREG_UV_BITS, DRV8305_STATUS03_WD_FAULT_BITS, DRV8305_STATUS04_FETHA_VGS_BITS, DRV8305_STATUS04_FETHB_VGS_BITS, DRV8305_STATUS04_FETHC_VGS_BITS, DRV8305_STATUS04_FETLA_VGS_BITS, DRV8305_STATUS04_FETLB_VGS_BITS, DRV8305_STATUS04_FETLC_VGS_BITS, DRV8305_STATUS04_RESERVED1_BITS, DRV8305_STATUS04_RESERVED2_BITS, DRV8305_STATUS04_RESERVED3_BITS, DRV8305_STATUS04_RESERVED4_BITS, DRV8305_STATUS04_RESERVED5_BITS, _DRV_SPI_8305_Ctrl09_t_::EN_SNS_CLAMP, _DRV_SPI_8305_Stat01_t_::FAULT, _DRV_SPI_8305_Stat02_t_::FETHA_VDS, _DRV_SPI_8305_Stat04_t_::FETHA_VGS, _DRV_SPI_8305_Stat02_t_::FETHB_VDS, _DRV_SPI_8305_Stat04_t_::FETHB_VGS, _DRV_SPI_8305_Stat02_t_::FETHC_VDS, _DRV_SPI_8305_Stat04_t_::FETHC_VGS, _DRV_SPI_8305_Stat02_t_::FETLA_VDS, _DRV_SPI_8305_Stat04_t_::FETLA_VGS, _DRV_SPI_8305_Stat02_t_::FETLB_VDS, _DRV_SPI_8305_Stat04_t_::FETLB_VGS, _DRV_SPI_8305_Stat02_t_::FETLC_VDS, _DRV_SPI_8305_Stat04_t_::FETLC_VGS, _DRV_SPI_8305_Ctrl09_t_::FLIP_OTS, _DRV_SPI_8305_Ctrl0A_t_::GAIN_CS1, _DRV_SPI_8305_Ctrl0A_t_::GAIN_CS2, _DRV_SPI_8305_Ctrl0A_t_::GAIN_CS3, _DRV_SPI_8305_Ctrl05_t_::IDRIVEN_HS, _DRV_SPI_8305_Ctrl06_t_::IDRIVEN_LS, _DRV_SPI_8305_Ctrl05_t_::IDRIVEP_HS, _DRV_SPI_8305_Ctrl06_t_::IDRIVEP_LS, _DRV_SPI_8305_Vars_t_::ManReadAddr, _DRV_SPI_8305_Vars_t_::ManReadCmd, _DRV_SPI_8305_Vars_t_::ManReadData, _DRV_SPI_8305_Vars_t_::ManWriteAddr, _DRV_SPI_8305_Vars_t_::ManWriteCmd, _DRV_SPI_8305_Vars_t_::ManWriteData, _DRV_SPI_8305_Stat03_t_::OTS, _DRV_SPI_8305_Stat01_t_::OTW, _DRV_SPI_8305_Stat01_t_::PVDD_OVFL, _DRV_SPI_8305_Stat01_t_::PVDD_UVFL, _DRV_SPI_8305_Stat03_t_::PVDD_UVLO2, _DRV_SPI_8305_Ctrl07_t_::PWM_MODE, _DRV_SPI_8305_Vars_t_::ReadCmd, _DRV_SPI_8305_Ctrl09_t_::SET_VCPH_UV, _DRV_SPI_8305_Ctrl09_t_::SLEEP, _DRV_SPI_8305_Ctrl0B_t_::SLP_DLY, _DRV_SPI_8305_Stat02_t_::SNS_A_OCP, _DRV_SPI_8305_Stat02_t_::SNS_B_OCP, _DRV_SPI_8305_Stat02_t_::SNS_C_OCP, _DRV_SPI_8305_Stat01_t_::STAT01_RSV1, _DRV_SPI_8305_Stat02_t_::STAT02_RSV1, _DRV_SPI_8305_Stat02_t_::STAT02_RSV2, _DRV_SPI_8305_Stat03_t_::STAT03_RSV1, _DRV_SPI_8305_Stat03_t_::STAT03_RSV2, _DRV_SPI_8305_Stat04_t_::STAT04_RSV1, _DRV_SPI_8305_Stat04_t_::STAT04_RSV2, _DRV_SPI_8305_Stat04_t_::STAT04_RSV3, _DRV_SPI_8305_Stat04_t_::STAT04_RSV4, _DRV_SPI_8305_Stat04_t_::STAT04_RSV5, _DRV_SPI_8305_Vars_t_::Stat_Reg_01, _DRV_SPI_8305_Vars_t_::Stat_Reg_02, _DRV_SPI_8305_Vars_t_::Stat_Reg_03, _DRV_SPI_8305_Vars_t_::Stat_Reg_04, _DRV_SPI_8305_Ctrl07_t_::TBLANK, _DRV_SPI_8305_Ctrl05_t_::TDRIVEN, _DRV_SPI_8305_Ctrl06_t_::TDRIVEP, _DRV_SPI_8305_Stat01_t_::TEMP_FLAG1, _DRV_SPI_8305_Stat01_t_::TEMP_FLAG2, _DRV_SPI_8305_Stat01_t_::TEMP_FLAG3, _DRV_SPI_8305_Stat01_t_::TEMP_FLAG4, _DRV_SPI_8305_Ctrl07_t_::TVDS, _DRV_SPI_8305_Stat03_t_::VCP_LSD_UVLO2, _DRV_SPI_8305_Stat03_t_::VCPH_OVLO, _DRV_SPI_8305_Stat03_t_::VCPH_OVLO_ABS, _DRV_SPI_8305_Stat01_t_::VCPH_UVFL, _DRV_SPI_8305_Stat03_t_::VCPH_UVLO2, _DRV_SPI_8305_Ctrl0C_t_::VDS_LEVEL, _DRV_SPI_8305_Ctrl0C_t_::VDS_MODE, _DRV_SPI_8305_Stat01_t_::VDS_STATUS, _DRV_SPI_8305_Ctrl0B_t_::VREF_SCALING, _DRV_SPI_8305_Stat03_t_::VREG_UV, _DRV_SPI_8305_Ctrl0B_t_::VREG_UV_LEVEL, _DRV_SPI_8305_Ctrl09_t_::WD_DLY, _DRV_SPI_8305_Ctrl09_t_::WD_EN, _DRV_SPI_8305_Stat03_t_::WD_FAULT, and _DRV_SPI_8305_Vars_t_::WriteCmd.
void DRV8305_setVDSBlanking (DRV8305_Handle handle, const DRV8305_CTRL07_VDSBlanking_e time)
Sets the VDS sense blanking time.
Parameters
[in] handle The DRV8305 handle
[in] time The blanking time time, us
Definition at line 586 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_TBLANK_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setVDSDeglitch (DRV8305_Handle handle, const DRV8305_CTRL07_VDSDeglitch_e time)
Sets the VDS sense deglitch time.
Parameters
[in] handle The DRV8305 handle
[in] time The deglitch time time, us
Definition at line 566 of file drv8305.c.
References Address_Control_7, DRV8305_CTRL07_TVDS_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setVDSLevel (DRV8305_Handle handle, const DRV8305_CTRL0C_VDSLevel_e level)
Sets the VDS OC level.
Parameters
[in] handle The DRV8305 handle
[in] level The VDS OC level, V
Definition at line 877 of file drv8305.c.
References Address_Control_C, DRV8305_CTRL0C_VDS_LEVEL_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setVDSMode (DRV8305_Handle handle, const DRV8305_CTRL0C_VDSMode_e mode)
Sets the VDS protection mode.
Parameters
[in] handle The DRV8305 handle
[in] mode The VDS protection mode
Definition at line 857 of file drv8305.c.
References Address_Control_C, DRV8305_CTRL0C_VDS_MODE_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setVrefScaling (DRV8305_Handle handle, const DRV8305_CTRL0B_VrefScaling_e mode)
Sets the VREF scaling factor.
Parameters
[in] handle The DRV8305 handle
[in] mode The VREF scaling factor
Definition at line 837 of file drv8305.c.
References Address_Control_B, DRV8305_CTRL0B_VREF_SCALING_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setVregUvLevel (DRV8305_Handle handle, const DRV8305_CTRL0B_VregUvLevel_e level)
Sets the under voltage level of VREF.
Parameters
[in] handle The DRV8305 handle
[in] level The UV level, %
Definition at line 797 of file drv8305.c.
References Address_Control_B, DRV8305_CTRL0B_VREG_UV_LEVEL_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_setWatchDelay (DRV8305_Handle handle, const DRV8305_CTRL09_WatchDelay_e time)
Sets the watchdog timer setting.
Parameters
[in] handle The DRV8305 handle
[in] time The watchdog timer setting, ms
Definition at line 666 of file drv8305.c.
References Address_Control_9, DRV8305_CTRL09_WD_DLY_BITS, DRV8305_readSpi(), and DRV8305_writeSpi().
void DRV8305_writeData (DRV8305_Handle handle, DRV_SPI_8305_Vars_t * Spi_8305_Vars)
Write to the DRV8305 SPI registers.
Parameters
[in] handle The DRV8305 handle
[in] Spi_8305_Vars The (DRV_SPI_8305_Vars_t) structure that contains all DRV8305 Status/Control register options
Definition at line 1153 of file drv8305.c.
References Address_Control_5, Address_Control_6, Address_Control_7, Address_Control_9, Address_Control_A, Address_Control_B, Address_Control_C, _DRV_SPI_8305_Ctrl09_t_::CLR_FLTS, _DRV_SPI_8305_Ctrl07_t_::COMM_OPT, _DRV_SPI_8305_Ctrl0A_t_::CS_BLANK, _DRV_SPI_8305_Ctrl05_t_::CTRL05_RSV1, _DRV_SPI_8305_Ctrl06_t_::CTRL06_RSV1, _DRV_SPI_8305_Ctrl07_t_::CTRL07_RSV1, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV1, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV2, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV3, _DRV_SPI_8305_Ctrl0B_t_::CTRL0B_RSV4, _DRV_SPI_8305_Ctrl0C_t_::CTRL0C_RSV1, _DRV_SPI_8305_Ctrl0C_t_::CTRL0C_RSV2, _DRV_SPI_8305_Ctrl0C_t_::CTRL0C_RSV3, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_05, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_06, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_07, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_09, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_0A, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_0B, _DRV_SPI_8305_Vars_t_::Ctrl_Reg_0C, _DRV_SPI_8305_Ctrl0A_t_::DC_CAL_CH1, _DRV_SPI_8305_Ctrl0A_t_::DC_CAL_CH2, _DRV_SPI_8305_Ctrl0A_t_::DC_CAL_CH3, _DRV_SPI_8305_Ctrl07_t_::DEAD_TIME, _DRV_SPI_8305_Ctrl09_t_::DIS_GDRV_FAULT, _DRV_SPI_8305_Ctrl0B_t_::DIS_PWRGD, _DRV_SPI_8305_Ctrl09_t_::DIS_SNS_OCP, _DRV_SPI_8305_Ctrl09_t_::DISABLE, DRV8305_writeSpi(), _DRV_SPI_8305_Ctrl09_t_::EN_SNS_CLAMP, _DRV_SPI_8305_Ctrl09_t_::FLIP_OTS, _DRV_SPI_8305_Ctrl0A_t_::GAIN_CS1, _DRV_SPI_8305_Ctrl0A_t_::GAIN_CS2, _DRV_SPI_8305_Ctrl0A_t_::GAIN_CS3, _DRV_SPI_8305_Ctrl05_t_::IDRIVEN_HS, _DRV_SPI_8305_Ctrl06_t_::IDRIVEN_LS, _DRV_SPI_8305_Ctrl05_t_::IDRIVEP_HS, _DRV_SPI_8305_Ctrl06_t_::IDRIVEP_LS, _DRV_SPI_8305_Vars_t_::ManWriteAddr, _DRV_SPI_8305_Vars_t_::ManWriteCmd, _DRV_SPI_8305_Vars_t_::ManWriteData, _DRV_SPI_8305_Ctrl07_t_::PWM_MODE, _DRV_SPI_8305_Ctrl09_t_::SET_VCPH_UV, _DRV_SPI_8305_Ctrl09_t_::SLEEP, _DRV_SPI_8305_Ctrl0B_t_::SLP_DLY, _DRV_SPI_8305_Ctrl07_t_::TBLANK, _DRV_SPI_8305_Ctrl05_t_::TDRIVEN, _DRV_SPI_8305_Ctrl06_t_::TDRIVEP, _DRV_SPI_8305_Ctrl07_t_::TVDS, _DRV_SPI_8305_Ctrl0C_t_::VDS_LEVEL, _DRV_SPI_8305_Ctrl0C_t_::VDS_MODE, _DRV_SPI_8305_Ctrl0B_t_::VREF_SCALING, _DRV_SPI_8305_Ctrl0B_t_::VREG_UV_LEVEL, _DRV_SPI_8305_Ctrl09_t_::WD_DLY, _DRV_SPI_8305_Ctrl09_t_::WD_EN, and _DRV_SPI_8305_Vars_t_::WriteCmd.
void DRV8305_writeSpi (DRV8305_Handle handle, const DRV8305_Address_e regAddr, const uint16_t data)
Writes data to the DRV8305 register.
Parameters
[in] handle The DRV8305 handle
[in] regAddr The register name
[in] data The data value
Definition at line 1129 of file drv8305.c.
References CtrlMode_Write, DRV8305_buildCtrlWord(), SPI_enableRxFifo(), SPI_resetRxFifo(), SPI_write(), and _DRV8305_Obj_::spiHandle.
Referenced by DRV8305_reset(), DRV8305_setCommOption(), DRV8305_setCSBlank(), DRV8305_setCSGain1(), DRV8305_setCSGain2(), DRV8305_setCSGain3(), DRV8305_setDcCalMode(), DRV8305_setDeadTime(), DRV8305_setPeakSinkCurHS(), DRV8305_setPeakSinkCurLS(), DRV8305_setPeakSinkTime(), DRV8305_setPeakSourCurHS(), DRV8305_setPeakSourTime(), DRV8305_setPwmMode(), DRV8305_setSleepDelay(), DRV8305_setVDSBlanking(), DRV8305_setVDSDeglitch(), DRV8305_setVDSLevel(), DRV8305_setVDSMode(), DRV8305_setVrefScaling(), DRV8305_setVregUvLevel(), DRV8305_setWatchDelay(), and DRV8305_writeData().