instaspin_foc: PROJ_LAB01
PROJ_LAB01
Modules
Project Overview
Macros
#define LED_BLINK_FREQ_Hz 5
Functions
void main (void)
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
Variables
uint_least32_t gLEDcnt = 0
HAL_Handle halHandle
The hal handle.
USER_Params gUserParams
The user parameters.
HAL_PwmData_t gPwmData = {0,0,0}
Defines the PWM data.
HAL_AdcData_t gAdcData = {0,0,0,0,0,0,0}
Defines the ADC data.
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
Detailed Description
Macro Definition Documentation
#define LED_BLINK_FREQ_Hz 5
Definition at line 68 of file proj_lab01.c.
Referenced by mainISR().
Function Documentation
void main (void)
Definition at line 116 of file proj_lab01.c.
References _MOTOR_Vars_t_::Flag_enableSys, hal, HAL_disablePwm(), HAL_enableAdcInts(), HAL_enableDebugInt(), HAL_enableDrv(), HAL_enableGlobalInts(), HAL_init(), HAL_initIntVectorTable(), HAL_setParams(), HAL_setupDrvSpi(), HAL_setupFaults(), memCopy(), USER_checkForErrors(), USER_getErrorCode(), USER_setParams(), and _MOTOR_Vars_t_::UserErrorCode.
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
Definition at line 222 of file proj_lab01.c.
References gLEDcnt, HAL_acqAdcInt(), HAL_readAdcData(), HAL_toggleLed, HAL_writePwmData(), LED_BLINK_FREQ_Hz, and USER_ISR_FREQ_Hz.
Variable Documentation
HAL_AdcData_t gAdcData = {0,0,0,0,0,0,0}
Defines the ADC data.
Definition at line 87 of file proj_lab01.c.
uint_least32_t gLEDcnt = 0
Definition at line 73 of file proj_lab01.c.
Referenced by mainISR().
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
Definition at line 89 of file proj_lab01.c.
HAL_PwmData_t gPwmData = {0,0,0}
Defines the PWM data.
Definition at line 85 of file proj_lab01.c.
USER_Params gUserParams
The user parameters.
Definition at line 83 of file proj_lab01.c.
HAL_Handle halHandle
The hal handle.
The hal handle.
Definition at line 78 of file proj_lab01.c.