instaspin_foc: fast_obs_pm_rs_rsol.c File Reference
fast_obs_pm_rs_rsol.c File Reference
#include "fast_obs.h"
Functions
void main (void)
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
void setupClarke_I (CLARKE_Handle handle, const uint_least8_t numCurrentSensors)
Sets the number of current sensors.
void setupClarke_V (CLARKE_Handle handle, const uint_least8_t numVoltageSensors)
Sets the number of voltage sensors.
void setupControllers (void)
Setups the controllers.
void updateGlobalVariables_motor (EST_Handle estHandle)
Updates the global motor variables.
void updateCPUusage (void)
Updates CPU usage.
Variables
EST_State_e gEstState = EST_State_Idle
Global variable for the estimator state.
volatile bool gFlag_enableSys = true
Global flag to enable/disable the system.
volatile bool gFlag_runOnLine = false
volatile bool gFlag_enableForceAngle = true
volatile bool gFlag_enableRsRecalc = true
volatile bool gFlag_enableRsOnLine = false
volatile bool gFlag_updateRs = false
float_t gFlux_Wb = 0.0
Global variable for the rotor flux estimate, Wb.
float_t gLs_d_H = 0.0
Global variable for the stator inductance in the direct coordinate direction, Henry.
float_t gLs_q_H = 0.0
Global variable for the stator inductance in the quadrature coordinate direction, Henry.
float_t gRsOnLine_Ohm = 0.0
float_t gRs_Ohm = 0.0
float_t gSpeed_Hz = 0.0
float_t gSpeed_ref_Hz = 10.0
volatile float_t gSpeed_Kp = 0.01
volatile float_t gSpeed_Ki = 0.001
volatile float_t gId_ref_A = 0.0
float_t gId_rs_recalc_ref_A = 0.0
float_t gIq_ref_A = 0.0
uint16_t gCounter_speed = 0
HAL_AdcData_t gAdcData
Defines the ADC data.
HAL_DacData_t gDacData
Defines the DAC data.
HAL_PwmData_t gPwmData
Defines the PWM data.
EST_InputData_t gEstInputData
EST_OutputData_t gEstOutputData
volatile float_t gRsOnLineFreq_Hz = 0.2
volatile float_t gRsOnLineId_mag_A = 0.5
volatile float_t gRsOnLinePole_Hz = 0.2
float_t gTorque_Nm = 0.0
Global variable for the estimated torque, N*m.
USER_Params gUserParams
The user parameters.
MATH_vec3 gOffsets_I_A = {0.0, 0.0, 0.0}
MATH_vec3 gOffsets_V_V = {0.0, 0.0, 0.0}
CLARKE_Handle clarkeHandle_I
the handle for the current Clarke transform
CLARKE_Obj clarke_I
the current Clarke transform object
CLARKE_Handle clarkeHandle_V
the handle for the voltage Clarke transform
CLARKE_Obj clarke_V
the voltage Clarke transform object
HAL_Handle halHandle
the handle for the hardware abstraction layer
HAL_Obj hal
the hardware abstraction layer object
EST_Handle estHandle
the handle for the estimator
IPARK_Handle iparkHandle
the handle for the inverse Park transform
IPARK_Obj ipark
the inverse Park transform object
PARK_Handle parkHandle
the handle for the Park object
PARK_Obj park
the Park transform object
PI_Handle piHandle_Id
the handle for the Id PI controller
PI_Obj pi_Id
the Id PI controller object
PI_Handle piHandle_Iq
the handle for the Iq PI controller
PI_Obj pi_Iq
the Iq PI controller object
PI_Handle piHandle_spd
the handle for the speed PI controller
PI_Obj pi_spd
the speed PI controller object
SVGEN_Handle svgenHandle
the handle for the space vector generator
SVGEN_Obj svgen
the space vector generator object
CPU_USAGE_Handle cpu_usageHandle
CPU_USAGE_Obj cpu_usage
float_t gCpuUsagePercentageMin = 0.0
float_t gCpuUsagePercentageAvg = 0.0
float_t gCpuUsagePercentageMax = 0.0
Function Documentation
void main (void)
Definition at line 128 of file fast_obs_pm_rs_rsol.c.
References CLARKE_init(), CPU_USAGE_init(), CPU_USAGE_setParams(), EST_disable(), EST_enable(), EST_initEst(), EST_setFlag_enableForceAngle(), EST_setFlag_enableRsOnLine(), EST_setFlag_enableRsRecalc(), EST_setFlag_updateRs(), EST_setParams(), EST_setRsOnLine_beta_rad(), EST_setRsOnLineAngleDelta_rad(), EST_setRsOnLineId_mag_A(), EST_updateState(), estHandle, gFlag_enableForceAngle, gFlag_enableRsOnLine, gFlag_enableRsRecalc, gFlag_enableSys, gFlag_runOnLine, gFlag_updateRs, gId_ref_A, gIq_ref_A, gRsOnLineFreq_Hz, gRsOnLineId_mag_A, gRsOnLinePole_Hz, gSpeed_Ki, gSpeed_Kp, HAL_disableGlobalInts(), HAL_disablePwm(), HAL_enableAdcInts(), HAL_enableDebugInt(), HAL_enableDrv(), HAL_enableGlobalInts(), HAL_enablePwm(), HAL_init(), HAL_initIntVectorTable(), HAL_readDrvData(), HAL_setParams(), HAL_setupDrvSpi(), HAL_setupFaults(), HAL_writeDrvData(), IPARK_init(), MATH_TWO_PI, _USER_Params_::numCurrentSensors, _USER_Params_::numVoltageSensors, PARK_init(), PI_init(), PI_setGains(), PI_setUi(), setupClarke_I(), setupClarke_V(), setupControllers(), SVGEN_init(), updateCPUusage(), updateGlobalVariables_motor(), USER_EST_FREQ_Hz, USER_ISR_FREQ_Hz, USER_setParams(), USER_SYSTEM_FREQ_MHz, _HAL_PwmData_t_::Vabc_pu, and _MATH_vec3_::value.
Variable Documentation
CLARKE_Obj clarke_I
the current Clarke transform object
Definition at line 86 of file fast_obs_pm_rs_rsol.c.
CLARKE_Obj clarke_V
the voltage Clarke transform object
Definition at line 89 of file fast_obs_pm_rs_rsol.c.
CLARKE_Handle clarkeHandle_I
the handle for the current Clarke transform
Definition at line 85 of file fast_obs_pm_rs_rsol.c.
CLARKE_Handle clarkeHandle_V
the handle for the voltage Clarke transform
Definition at line 88 of file fast_obs_pm_rs_rsol.c.
CPU_USAGE_Obj cpu_usage
Definition at line 120 of file fast_obs_pm_rs_rsol.c.
CPU_USAGE_Handle cpu_usageHandle
Definition at line 119 of file fast_obs_pm_rs_rsol.c.
EST_Handle estHandle
the handle for the estimator
Definition at line 94 of file fast_obs_pm_rs_rsol.c.
Referenced by main(), and mainISR().
uint16_t gCounter_speed = 0
Definition at line 59 of file fast_obs_pm_rs_rsol.c.
Referenced by mainISR().
float_t gCpuUsagePercentageAvg = 0.0
Definition at line 122 of file fast_obs_pm_rs_rsol.c.
Referenced by updateCPUusage().
float_t gCpuUsagePercentageMax = 0.0
Definition at line 123 of file fast_obs_pm_rs_rsol.c.
Referenced by updateCPUusage().
float_t gCpuUsagePercentageMin = 0.0
Definition at line 121 of file fast_obs_pm_rs_rsol.c.
Referenced by updateCPUusage().
EST_InputData_t gEstInputData
Definition at line 67 of file fast_obs_pm_rs_rsol.c.
EST_OutputData_t gEstOutputData
Definition at line 69 of file fast_obs_pm_rs_rsol.c.
volatile bool gFlag_enableForceAngle = true
Definition at line 27 of file fast_obs_pm_rs_rsol.c.
Referenced by main().
volatile bool gFlag_enableRsOnLine = false
Definition at line 31 of file fast_obs_pm_rs_rsol.c.
Referenced by main().
volatile bool gFlag_enableRsRecalc = true
Definition at line 29 of file fast_obs_pm_rs_rsol.c.
Referenced by main().
volatile bool gFlag_runOnLine = false
Definition at line 25 of file fast_obs_pm_rs_rsol.c.
Referenced by main().
volatile bool gFlag_updateRs = false
Definition at line 33 of file fast_obs_pm_rs_rsol.c.
Referenced by main().
volatile float_t gId_ref_A = 0.0
Definition at line 53 of file fast_obs_pm_rs_rsol.c.
Referenced by main(), and mainISR().
float_t gId_rs_recalc_ref_A = 0.0
Definition at line 55 of file fast_obs_pm_rs_rsol.c.
Referenced by mainISR().
float_t gIq_ref_A = 0.0
Definition at line 57 of file fast_obs_pm_rs_rsol.c.
Referenced by main(), and mainISR().
MATH_vec3 gOffsets_I_A = {0.0, 0.0, 0.0}
Definition at line 81 of file fast_obs_pm_rs_rsol.c.
MATH_vec3 gOffsets_V_V = {0.0, 0.0, 0.0}
Definition at line 83 of file fast_obs_pm_rs_rsol.c.
float_t gRs_Ohm = 0.0
Definition at line 43 of file fast_obs_pm_rs_rsol.c.
Referenced by updateGlobalVariables_motor().
float_t gRsOnLine_Ohm = 0.0
Definition at line 41 of file fast_obs_pm_rs_rsol.c.
Referenced by updateGlobalVariables_motor().
volatile float_t gRsOnLineFreq_Hz = 0.2
Definition at line 71 of file fast_obs_pm_rs_rsol.c.
Referenced by main().
volatile float_t gRsOnLineId_mag_A = 0.5
Definition at line 73 of file fast_obs_pm_rs_rsol.c.
Referenced by main().
volatile float_t gRsOnLinePole_Hz = 0.2
Definition at line 75 of file fast_obs_pm_rs_rsol.c.
Referenced by main().
float_t gSpeed_Hz = 0.0
Definition at line 45 of file fast_obs_pm_rs_rsol.c.
Referenced by updateGlobalVariables_motor().
volatile float_t gSpeed_Ki = 0.001
Definition at line 51 of file fast_obs_pm_rs_rsol.c.
Referenced by main(), and setupControllers().
volatile float_t gSpeed_Kp = 0.01
Definition at line 49 of file fast_obs_pm_rs_rsol.c.
Referenced by main(), and setupControllers().
float_t gSpeed_ref_Hz = 10.0
Definition at line 47 of file fast_obs_pm_rs_rsol.c.
Referenced by mainISR().
HAL_Obj hal
the hardware abstraction layer object
Definition at line 92 of file fast_obs_pm_rs_rsol.c.
IPARK_Obj ipark
the inverse Park transform object
Definition at line 97 of file fast_obs_pm_rs_rsol.c.
IPARK_Handle iparkHandle
the handle for the inverse Park transform
Definition at line 96 of file fast_obs_pm_rs_rsol.c.
PARK_Obj park
the Park transform object
Definition at line 100 of file fast_obs_pm_rs_rsol.c.
PARK_Handle parkHandle
the handle for the Park object
Definition at line 99 of file fast_obs_pm_rs_rsol.c.
PI_Obj pi_Id
the Id PI controller object
Definition at line 103 of file fast_obs_pm_rs_rsol.c.
PI_Obj pi_Iq
the Iq PI controller object
Definition at line 106 of file fast_obs_pm_rs_rsol.c.
PI_Obj pi_spd
the speed PI controller object
Definition at line 109 of file fast_obs_pm_rs_rsol.c.
PI_Handle piHandle_Id
the handle for the Id PI controller
Definition at line 102 of file fast_obs_pm_rs_rsol.c.
PI_Handle piHandle_Iq
the handle for the Iq PI controller
Definition at line 105 of file fast_obs_pm_rs_rsol.c.
PI_Handle piHandle_spd
the handle for the speed PI controller
Definition at line 108 of file fast_obs_pm_rs_rsol.c.
SVGEN_Obj svgen
the space vector generator object
Definition at line 112 of file fast_obs_pm_rs_rsol.c.
SVGEN_Handle svgenHandle
the handle for the space vector generator
Definition at line 111 of file fast_obs_pm_rs_rsol.c.